export const ACCOUNTING_PROGRAMS = [
  { value: "rivile", label: "Rivilė GAMA" },
  { value: "rivile_erp", label: "Rivilė ERP" },
  // { value: "bss", label: "BSS Buhalterija" },
  { value: "finvalda", label: "Finvalda" },
  { value: "centas", label: "Centas" },
  { value: "agnum", label: "Agnum" },
  { value: "apskaita5", label: "Apskaita5" },
  { value: "pragma3", label: "Pragma 3.2" },
  { value: "pragma4", label: "Pragma 4" },
  { value: "butent", label: "Būtent" },
  { value: "dineta", label: "Dineta" },
  { value: "optimum", label: "Optimum" },
  { value: "debetas", label: "Debetas" },
].sort((a, b) => a.label.localeCompare(b.label));