export const COUNTRY_OPTIONS = [
  { code: "LT", name: "Lietuva" },
  { code: "AD", name: "Andora" },
  { code: "AE", name: "Jungtiniai Arabų Emyratai" },
  { code: "AF", name: "Afganistanas" },
  { code: "AG", name: "Antigva ir Barbuda" },
  { code: "AI", name: "Angilija" },
  { code: "AL", name: "Albanija" },
  { code: "AM", name: "Armėnija" },
  { code: "AO", name: "Angola" },
  { code: "AQ", name: "Antarktida" },
  { code: "AR", name: "Argentina" },
  { code: "AS", name: "Samoa" },
  { code: "AT", name: "Austrija" },
  { code: "AU", name: "Australija" },
  { code: "AW", name: "Aruba" },
  { code: "AZ", name: "Azerbaidžanas" },
  { code: "BA", name: "Bosnija ir Hercegovina" },
  { code: "BB", name: "Barbadosas" },
  { code: "BD", name: "Bangladešas" },
  { code: "BE", name: "Belgija" },
  { code: "BF", name: "Burkina Fasas" },
  { code: "BG", name: "Bulgarija" },
  { code: "BH", name: "Bahreinas" },
  { code: "BI", name: "Burundis" },
  { code: "BY", name: "Baltarusija" },
  { code: "BJ", name: "Beninas" },
  { code: "BL", name: "Sen Bartelemi" },
  { code: "BM", name: "Bermudai" },
  { code: "BN", name: "Brunėjus" },
  { code: "BO", name: "Bolivija" },
  { code: "BQ", name: "Boneras, Sint Eustatijus ir Saba" },
  { code: "BR", name: "Brazilija" },
  { code: "BS", name: "Bahamos" },
  { code: "BT", name: "Butanas" },
  { code: "BV", name: "Bouvet sala" },
  { code: "BW", name: "Botsvana" },
  { code: "BZ", name: "Belizas" },
  { code: "CA", name: "Kanada" },
  { code: "CC", name: "Kokosų (Kilingo) Salos" },
  { code: "CD", name: "Kongo Demokratinė Respublika" },
  { code: "CF", name: "Centrinės Afrikos Respublika" },
  { code: "CG", name: "Kongas" },
  { code: "CH", name: "Šveicarija" },
  { code: "CI", name: "Dramblio Kaulo Krantas" },
  { code: "CY", name: "Kipras" },
  { code: "CK", name: "Kuko salos" },
  { code: "CL", name: "Čilė" },
  { code: "CM", name: "Kamerūnas" },
  { code: "CN", name: "Kinija" },
  { code: "CO", name: "Kolumbija" },
  { code: "CR", name: "Kosta Rika" },
  { code: "CU", name: "Kuba" },
  { code: "CV", name: "Žaliasis Kyšulys" },
  { code: "CW", name: "Kiurasao" },
  { code: "CX", name: "Kalėdų sala" },
  { code: "CZ", name: "Čekija" },
  { code: "DE", name: "Vokietija" },
  { code: "DJ", name: "Džibutis" },
  { code: "DK", name: "Danija" },
  { code: "DM", name: "Dominika" },
  { code: "DO", name: "Dominikos Respublika" },
  { code: "DZ", name: "Alžyras" },
  { code: "EC", name: "Ekvadoras" },
  { code: "EE", name: "Estija" },
  { code: "EG", name: "Egiptas" },
  { code: "EH", name: "Vakarų Sachara" },
  { code: "ER", name: "Eritrėja" },
  { code: "ES", name: "Ispanija" },
  { code: "ET", name: "Etiopija" },
  { code: "EU", name: "Europos Sąjunga" },
  { code: "FI", name: "Suomija" },
  { code: "FJ", name: "Fidžis" },
  { code: "FK", name: "Folklando Salos" },
  { code: "FM", name: "Mikronezijos Federacines Valstijos" },
  { code: "FO", name: "Farerų salos" },
  { code: "FR", name: "Prancūzija" },
  { code: "GA", name: "Gabonas" },
  { code: "GB", name: "Didžioji Britanija" },
  { code: "GD", name: "Grenada" },
  { code: "GE", name: "Gruzija" },
  { code: "GH", name: "Gana" },
  { code: "GI", name: "Gibraltaras" },
  { code: "GY", name: "Gajana" },
  { code: "GL", name: "Grenlandija" },
  { code: "GM", name: "Gambija" },
  { code: "GN", name: "Gvinėja" },
  { code: "GQ", name: "Pusiaujo Gvinėja" },
  { code: "GR", name: "Graikija" },
  { code: "GS", name: "Pietų Džordžijos ir Pietų Sendvičo Salos" },
  { code: "GT", name: "Gvatemala" },
  { code: "GU", name: "Guamas" },
  { code: "GW", name: "Bisau Gvinėja" },
  { code: "HK", name: "Honkongas" },
  { code: "HM", name: "Heardo ir Mc Donaldo salos" },
  { code: "HN", name: "Hondūras" },
  { code: "HR", name: "Kroatija" },
  { code: "HT", name: "Haitis" },
  { code: "HU", name: "Vengrija" },
  { code: "ID", name: "Indonezija" },
  { code: "IE", name: "Airija" },
  { code: "YE", name: "Jemenas" },
  { code: "IL", name: "Izraelis" },
  { code: "IN", name: "Indija" },
  { code: "IO", name: "Indijos Vandenyno Britu Sritis" },
  { code: "IQ", name: "Irakas" },
  { code: "IR", name: "Irano Islamo Respublika" },
  { code: "IS", name: "Islandija" },
  { code: "IT", name: "Italija" },
  { code: "YT", name: "Mayotte'as" },
  { code: "JM", name: "Jamaika" },
  { code: "JO", name: "Jordanija" },
  { code: "JP", name: "Japonija" },
  { code: "KE", name: "Kenija" },
  { code: "KG", name: "Kirgizija" },
  { code: "KH", name: "Kambodža" },
  { code: "KI", name: "Kiribatis" },
  { code: "KY", name: "Kaimanų salos" },
  { code: "KM", name: "Komorai" },
  { code: "KN", name: "Sent Kitsas ir Nevis" },
  { code: "KP", name: "Šiaurės Korėja" },
  { code: "KR", name: "Pietų Korėja" },
  { code: "KW", name: "Kuveitas" },
  { code: "KZ", name: "Kazachstanas" },
  { code: "LA", name: "Laosas" },
  { code: "LB", name: "Libanas" },
  { code: "LC", name: "Sent Lusija" },
  { code: "LI", name: "Lichtenšteinas" },
  { code: "LY", name: "Libija" },
  { code: "LK", name: "Šri Lanka" },
  { code: "LR", name: "Liberija" },
  { code: "LS", name: "Lesotas" },
  { code: "LU", name: "Liuksemburgas" },
  { code: "LV", name: "Latvija" },
  { code: "MA", name: "Marokas" },
  { code: "MD", name: "Moldavija, Moldovos Respublika" },
  { code: "ME", name: "Juodkalnija" },
  { code: "MG", name: "Madagaskaras" },
  { code: "MH", name: "Maršalo Salos" },
  { code: "MY", name: "Malaizija" },
  { code: "MK", name: "Makedonija" },
  { code: "ML", name: "Malis" },
  { code: "MM", name: "Mianmaras" },
  { code: "MN", name: "Mongolija" },
  { code: "MO", name: "Macao" },
  { code: "MP", name: "Marianos šiaurinės salos" },
  { code: "MR", name: "Mauritanija" },
  { code: "MS", name: "Montserratas" },
  { code: "MT", name: "Malta" },
  { code: "MU", name: "Mauricijus" },
  { code: "MV", name: "Maldyvai" },
  { code: "MW", name: "Malavis" },
  { code: "MX", name: "Meksika" },
  { code: "MZ", name: "Mozambikas" },
  { code: "NA", name: "Namibija" },
  { code: "NC", name: "Naujoji Kaledonija ir priklausoma teritorija" },
  { code: "NE", name: "Nigeris" },
  { code: "NF", name: "Norfolko sala" },
  { code: "NG", name: "Nigerija" },
  { code: "NI", name: "Nikaragva" },
  { code: "NL", name: "Olandija" },
  { code: "NO", name: "Norvegija" },
  { code: "NP", name: "Nepalas" },
  { code: "NR", name: "Nauru" },
  { code: "NU", name: "Niujė sala" },
  { code: "NZ", name: "Naujoji Zelandija" },
  { code: "OM", name: "Omanas" },
  { code: "PA", name: "Panama" },
  { code: "PE", name: "Peru" },
  { code: "PF", name: "Prancūzijos Polinezija" },
  { code: "PG", name: "Papua Naujoji Gvinėja" },
  { code: "PH", name: "Filipinai" },
  { code: "PY", name: "Paragvajus" },
  { code: "PK", name: "Pakistanas" },
  { code: "PL", name: "Lenkija" },
  { code: "PM", name: "Sent Pjeras ir Mikelonas" },
  { code: "PN", name: "Pitcairno salos" },
  { code: "PS", name: "Okupuota Palestinos teritorija" },
  { code: "PT", name: "Portugalija" },
  { code: "PW", name: "Palau" },
  { code: "QA", name: "Kataras" },
  { code: "QY", name: "Dėl prekybos ar karinių priežasčių vykdant ES vidaus prekybą nenurodytos šalys ir teritorijos" },
  { code: "QP", name: "Atvira jura (Jūrų sritis, nepriklausanti teritoriniams vandenims)" },
  { code: "QQ", name: "Aprūpinimas ir tiekimas" },
  { code: "QR", name: "Atsargos ir maisto atsargos, tiekiamos vykdant ES vidaus prekybą" },
  { code: "QS", name: "Aprūpinimas ir tiekimas trečiųjų šalių prekybos erdvėje" },
  { code: "QU", name: "Kitur nenurodytos valstybės ir teritorijos" },
  { code: "QV", name: "Šalys ir teritorijos, nenurodytos vykdant ES vidaus prekybą" },
  { code: "QW", name: "Valstybės ir teritorijos nenurodytos Trečiųjų salių prekybos erdvėje" },
  { code: "QX", name: "Valstybės ir teritorijos nenurodytos kaip skirtos komerciniams ir kariniams tikslams" },
  { code: "QZ", name: "QX Trečiųjų šalių prekybos erdvėje" },
  { code: "RO", name: "Rumunija" },
  { code: "RU", name: "Rusijos Federacija" },
  { code: "RW", name: "Ruanda" },
  { code: "SA", name: "Saudo Arabija" },
  { code: "SB", name: "Saliamono salos" },
  { code: "SC", name: "Seišeliai" },
  { code: "SD", name: "Sudanas" },
  { code: "SE", name: "Švedija" },
  { code: "SG", name: "Singapūras" },
  { code: "SH", name: "Šv. Elenos, Dangun Žengimo ir Tristano da Kunjos Salos" },
  { code: "SI", name: "Slovėnija" },
  { code: "SY", name: "Sirija" },
  { code: "SK", name: "Slovakija" },
  { code: "SL", name: "Siera Leonė" },
  { code: "SM", name: "San Marinas" },
  { code: "SN", name: "Senegalas" },
  { code: "SO", name: "Somalis" },
  { code: "SR", name: "Surinamas" },
  { code: "SS", name: "Pietu Sudanas" },
  { code: "ST", name: "San Tomė ir ir Prinsipė" },
  { code: "SV", name: "Salvadoras" },
  { code: "SX", name: "Sint Martenas (Nyderlandų dalis)" },
  { code: "SZ", name: "Svazilandas" },
  { code: "TC", name: "Turkso ir Caicoso salos" },
  { code: "TD", name: "Čadas" },
  { code: "TF", name: "Prancuzijos Pietu Sritys" },
  { code: "TG", name: "Togas" },
  { code: "TH", name: "Tailandas" },
  { code: "TJ", name: "Tadžikistanas" },
  { code: "TK", name: "Tokelau" },
  { code: "TL", name: "Rytų Timoras" },
  { code: "TM", name: "Turkmėnistanas" },
  { code: "TN", name: "Tunisas" },
  { code: "TO", name: "Tonga" },
  { code: "TR", name: "Turkija" },
  { code: "TT", name: "Trinidadas ir Tobagas" },
  { code: "TV", name: "Tuvalu" },
  { code: "TW", name: "Taivanas" },
  { code: "TZ", name: "Tanzanijos Jungtine Respublika" },
  { code: "UA", name: "Ukraina" },
  { code: "UG", name: "Uganda" },
  { code: "UY", name: "Urugvajus" },
  { code: "UM", name: "Jungtinių Valstijų aplinkinės smulkiosios salos (United States Minor outlying islands)" },
  { code: "US", name: "Jungtinės Valstijos, JAV" },
  { code: "UZ", name: "Uzbekistanas" },
  { code: "VA", name: "Vatikanas" },
  { code: "VC", name: "Sent Vinsentas ir Grenadinai" },
  { code: "VE", name: "Venesuela" },
  { code: "VG", name: "Didžiosios Britanijos Mergelių Salos" },
  { code: "VI", name: "Mergelių salos (JAV)" },
  { code: "VN", name: "Vietnamas" },
  { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Walliso ir Futunos salos" },
  { code: "WS", name: "Samoa" },
  { code: "XC", name: "Seuta" },
  { code: "XK", name: "Kosovas (Kaip nustatyta 1999 m. birželio 10d. Jungtinių Tautų Saugumo Tarybos rezoliucijoje Nr.1244)" },
  { code: "XL", name: "Melilija" },
  { code: "XS", name: "Serbija" },
  { code: "ZA", name: "Pietų Afrika" },
  { code: "ZM", name: "Zambija" },
  { code: "ZW", name: "Zimbabvė" },
]