# Generated by Django 4.2.16 on 2025-07-31 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import docscanner_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subscription_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "subscription_plan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "default_accounting_program",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rivile", "Rivilė"),
                            ("bss", "BSS"),
                            ("finvalda", "Finvalda"),
                            ("centas", "Centas"),
                            ("apskaita5", "Apskaita5"),
                            ("centas", "Centas"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Įmonės pavadinimas",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "vat_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "company_iban",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Įmonės IBAN",
                    ),
                ),
                (
                    "company_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Įmonės adresas",
                    ),
                ),
                (
                    "company_country_iso",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Įmonės šalis",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PVMKlasifikatoriai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodas", models.CharField(max_length=16, unique=True)),
                ("aprasymas", models.TextField()),
                ("tarifas", models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScannedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(upload_to=docscanner_app.models.user_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Vykdomi"),
                            ("completed", "Atlikti (Neeksportuoti)"),
                            ("rejected", "Atmesti"),
                            ("exported", "Atlikti (Eksportuoti)"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("preview_url", models.URLField(blank=True, null=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("sumiskai", "Sumiškai"), ("detaliai", "Detaliai")],
                        default="sumiskai",
                        max_length=32,
                    ),
                ),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("structured_json", models.JSONField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "similarity_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pirkimas_pardavimas",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pirkimas", "Pirkimas"),
                            ("pardavimas", "Pardavimas"),
                            ("nezinoma", "Nežinoma"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "seller_id_programoje",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("seller_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "seller_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_vat_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "seller_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "seller_country_iso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "seller_iban",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seller_is_person", models.BooleanField(blank=True, null=True)),
                (
                    "buyer_id_programoje",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("buyer_id", models.CharField(blank=True, max_length=100, null=True)),
                ("buyer_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buyer_vat_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "buyer_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "buyer_country_iso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("buyer_iban", models.CharField(blank=True, max_length=255, null=True)),
                ("buyer_is_person", models.BooleanField(blank=True, null=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("operation_date", models.DateField(blank=True, null=True)),
                (
                    "document_series",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "amount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "invoice_discount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "invoice_discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("separate_vat", models.BooleanField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=20, null=True)),
                ("with_receipt", models.BooleanField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("report_to_isaf", models.BooleanField(blank=True, null=True)),
                (
                    "document_type_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("xml_source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Prekės kodas",
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Prekės barkodas",
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Prekės pavadinimas",
                    ),
                ),
                (
                    "prekes_tipas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Prekės tipas",
                    ),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Sandėlio kodas",
                    ),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sandėlio pavadinimas",
                    ),
                ),
                (
                    "objekto_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Objekto kodas",
                    ),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Objekto pavadinimas",
                    ),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Padalinio kodas",
                    ),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Padalinio pavadinimas",
                    ),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Mokesčio kodas",
                    ),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mokesčio pavadinimas",
                    ),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Atsakingo asmens kodas",
                    ),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Atsakingo asmens pavadinimas",
                    ),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Operacijos kodas",
                    ),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Operacijos pavadinimas",
                    ),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Išlaidų straipsnio kodas",
                    ),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Išlaidų straipsnio pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "pvm_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="PVM pavadinimas",
                    ),
                ),
                (
                    "tipo_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Tipo kodas"
                    ),
                ),
                (
                    "tipo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tipo pavadinimas",
                    ),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Žurnalo kodas",
                    ),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Žurnalo pavadinimas",
                    ),
                ),
                (
                    "projekto_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Projekto kodas",
                    ),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Projekto pavadinimas",
                    ),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Projekto vadovo kodas",
                    ),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Projekto vadovo pavadinimas",
                    ),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Skyriaus kodas",
                    ),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Skyriaus pavadinimas",
                    ),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Partijos nr. kodas",
                    ),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Partijos nr. pavadinimas",
                    ),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Korespondencijos kodas",
                    ),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Korespondencijos pavadinimas",
                    ),
                ),
                (
                    "serijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Serijos kodas",
                    ),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Serijos pavadinimas",
                    ),
                ),
                (
                    "centro_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Centro kodas",
                    ),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Centro pavadinimas",
                    ),
                ),
                ("val_ar_sutapo", models.BooleanField(blank=True, null=True)),
                ("val_subtotal_match", models.BooleanField(blank=True, null=True)),
                ("val_vat_match", models.BooleanField(blank=True, null=True)),
                ("val_total_match", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAutocomplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Prekės kodas",
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Prekės barkodas",
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Prekės pavadinimas",
                    ),
                ),
                (
                    "prekes_tipas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Prekės tipas",
                    ),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Sandėlio kodas",
                    ),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sandėlio pavadinimas",
                    ),
                ),
                (
                    "objekto_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Objekto kodas",
                    ),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Objekto pavadinimas",
                    ),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Padalinio kodas",
                    ),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Padalinio pavadinimas",
                    ),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Mokesčio kodas",
                    ),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mokesčio pavadinimas",
                    ),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Atsakingo asmens kodas",
                    ),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Atsakingo asmens pavadinimas",
                    ),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Operacijos kodas",
                    ),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Operacijos pavadinimas",
                    ),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Išlaidų straipsnio kodas",
                    ),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Išlaidų straipsnio pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "pvm_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="PVM pavadinimas",
                    ),
                ),
                (
                    "tipo_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Tipo kodas"
                    ),
                ),
                (
                    "tipo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tipo pavadinimas",
                    ),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Žurnalo kodas",
                    ),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Žurnalo pavadinimas",
                    ),
                ),
                (
                    "projekto_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Projekto kodas",
                    ),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Projekto pavadinimas",
                    ),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Projekto vadovo kodas",
                    ),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Projekto vadovo pavadinimas",
                    ),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Skyriaus kodas",
                    ),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Skyriaus pavadinimas",
                    ),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Partijos nr. kodas",
                    ),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Partijos nr. pavadinimas",
                    ),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Korespondencijos kodas",
                    ),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Korespondencijos pavadinimas",
                    ),
                ),
                (
                    "serijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Serijos kodas",
                    ),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Serijos pavadinimas",
                    ),
                ),
                (
                    "centro_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Centro kodas",
                    ),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Centro pavadinimas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_autocomplete",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prekės autocomplete įrašas",
                "verbose_name_plural": "Prekės autocomplete įrašai",
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Prekės kodas"
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Prekės barkodas"
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Prekės pavadinimas"
                    ),
                ),
                (
                    "prekes_tipas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Prekės tipas"
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Sandėlio kodas",
                    ),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sandėlio pavadinimas",
                    ),
                ),
                (
                    "objekto_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Objekto kodas",
                    ),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Objekto pavadinimas",
                    ),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Padalinio kodas",
                    ),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Padalinio pavadinimas",
                    ),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Mokesčio kodas",
                    ),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mokesčio pavadinimas",
                    ),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Atsakingo asmens kodas",
                    ),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Atsakingo asmens pavadinimas",
                    ),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Operacijos kodas",
                    ),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Operacijos pavadinimas",
                    ),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Išlaidų straipsnio kodas",
                    ),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Išlaidų straipsnio pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "pvm_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="PVM pavadinimas",
                    ),
                ),
                (
                    "tipo_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Tipo kodas"
                    ),
                ),
                (
                    "tipo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tipo pavadinimas",
                    ),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Žurnalo kodas",
                    ),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Žurnalo pavadinimas",
                    ),
                ),
                (
                    "projekto_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Projekto kodas",
                    ),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Projekto pavadinimas",
                    ),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Projekto vadovo kodas",
                    ),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Projekto vadovo pavadinimas",
                    ),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Skyriaus kodas",
                    ),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Skyriaus pavadinimas",
                    ),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Partijos nr. kodas",
                    ),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Partijos nr. pavadinimas",
                    ),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Korespondencijos kodas",
                    ),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Korespondencijos pavadinimas",
                    ),
                ),
                (
                    "serijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Serijos kodas",
                    ),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Serijos pavadinimas",
                    ),
                ),
                (
                    "centro_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Centro kodas",
                    ),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Centro pavadinimas",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientAutocomplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kodas_programoje",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Kliento kodas programoje",
                    ),
                ),
                (
                    "imones_kodas",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        verbose_name="Imonės kodas",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "ibans",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="IBANs (per kablelį, jei keli)",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("country_iso", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Klientas autocomplete įrašas",
                "verbose_name_plural": "Klientai autocomplete įrašai",
            },
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(fields=["user"], name="docscanner__user_id_bc3664_idx"),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["uploaded_at"], name="docscanner__uploade_7257ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["seller_name"], name="docscanner__seller__2331cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productautocomplete",
            index=models.Index(
                fields=["user", "prekes_kodas"], name="docscanner__user_id_4c0dd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientautocomplete",
            index=models.Index(
                fields=["user", "imones_kodas"], name="docscanner__user_id_f31e32_idx"
            ),
        ),
    ]
