# Generated by Django 4.2.16 on 2025-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="gpt_raw_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
