# Generated by Django 4.2.16 on 2025-06-30 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docscanner_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(upload_to=docscanner_app.models.user_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("structured_json", models.JSONField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "seller_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=255, null=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("operation_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_series",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vat_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "amount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
