# Generated by Django 4.2.16 on 2025-08-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0002_scanneddocument_gpt_raw_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(db_index=True, max_length=8)),
                ("date", models.DateField(db_index=True)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=15)),
                ("checked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "currency"],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
