# Generated by Django 4.2.16 on 2025-06-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0002_scanneddocument"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(fields=["user"], name="docscanner__user_id_bc3664_idx"),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["uploaded_at"], name="docscanner__uploade_7257ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["seller_name"], name="docscanner__seller__2331cc_idx"
            ),
        ),
    ]
