# Generated by Django 4.2.16 on 2025-08-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0003_currencyrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="prekes_paslauga",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Preke_paslauga"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="prekes_paslauga",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Preke_paslauga"
            ),
        ),
    ]
