# Generated by Django 4.2.16 on 2025-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0003_scanneddocument_docscanner__user_id_bc3664_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneddocument",
            name="operation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
