# Generated by Django 4.2.16 on 2025-08-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0004_lineitem_prekes_paslauga_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineitem",
            old_name="prekes_paslauga",
            new_name="preke_paslauga",
        ),
        migrations.RenameField(
            model_name="scanneddocument",
            old_name="prekes_paslauga",
            new_name="preke_paslauga",
        ),
    ]
