# Generated by Django 4.2.16 on 2025-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0005_customuser_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="subscription_end_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscription_start_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="subscription_status",
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="preview_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Vykdomi"),
                    ("completed", "Atlikti (Neeksportuoti)"),
                    ("rejected", "Atmesti"),
                    ("exported", "Atlikti (Eksportuoti)"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
