# Generated by Django 4.2.16 on 2025-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0005_rename_prekes_paslauga_lineitem_preke_paslauga_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("im_kodas", models.CharField(db_index=True, max_length=16)),
                ("pavadinimas", models.CharField(db_index=True, max_length=255)),
                ("ireg_data", models.DateField(blank=True, null=True)),
                ("isreg_data", models.DateField(blank=True, null=True)),
                ("tipas", models.CharField(blank=True, max_length=64)),
                ("pvm_kodas", models.CharField(blank=True, max_length=32)),
                ("pvm_ireg", models.DateField(blank=True, null=True)),
                ("pvm_isreg", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Company",
                "indexes": [
                    models.Index(
                        fields=["im_kodas"], name="docscanner__im_koda_e5674d_idx"
                    ),
                    models.Index(
                        fields=["pavadinimas"], name="docscanner__pavadin_1fd544_idx"
                    ),
                    models.Index(
                        fields=["pvm_kodas"], name="docscanner__pvm_kod_3d4e63_idx"
                    ),
                ],
            },
        ),
    ]
