# Generated by Django 4.2.16 on 2025-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0006_alter_customuser_default_accounting_program_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="im_kodas",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="pavadinimas",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="pvm_kodas",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="tipas",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
