# Generated by Django 4.2.16 on 2025-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0006_remove_customuser_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_plan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
