# Generated by Django 4.2.16 on 2025-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0007_customuser_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription_plan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
