# Generated by Django 4.2.16 on 2025-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0008_adclick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="prekes_barkodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės barkodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="prekes_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="prekes_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prekės pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="prekes_tipas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės tipas"
            ),
        ),
    ]
