# Generated by Django 4.2.16 on 2025-07-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0008_alter_customuser_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="similarity_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
