# Generated by Django 4.2.16 on 2025-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0009_alter_lineitem_prekes_barkodas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="paid_by_cash",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
