# Generated by Django 4.2.16 on 2025-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0009_scanneddocument_similarity_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("centas", "Centas"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
