# Generated by Django 4.2.16 on 2025-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0010_scanneddocument_paid_by_cash"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="currencyrate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="currencyrate",
            constraint=models.UniqueConstraint(
                fields=("currency", "date"), name="uniq_currency_date"
            ),
        ),
    ]
