# Generated by Django 4.2.16 on 2025-07-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0011_alter_customuser_default_accounting_program_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apskaita5autocomplete",
            name="docscanner__user_id_d057bc_idx",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="islaidos_prekes_kodas",
            new_name="apsk5_islaidos_prekes_kodas",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="islaidos_prekes_pavadinimas",
            new_name="apsk5_islaidos_prekes_pavadinimas",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="klientai_iban",
            new_name="apsk5_klientai_iban",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="klientai_imones_kodas",
            new_name="apsk5_klientai_imones_kodas",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="klientai_kodas_programoje",
            new_name="apsk5_klientai_kodas_programoje",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="klientai_pavadinimas",
            new_name="apsk5_klientai_pavadinimas",
        ),
        migrations.RenameField(
            model_name="apskaita5autocomplete",
            old_name="klientai_pvm_kodas",
            new_name="apsk5_klientai_pvm_kodas",
        ),
        migrations.RemoveField(
            model_name="apskaita5autocomplete",
            name="created_at",
        ),
        migrations.AddIndex(
            model_name="apskaita5autocomplete",
            index=models.Index(
                fields=["user", "apsk5_klientai_imones_kodas"],
                name="docscanner__user_id_47c686_idx",
            ),
        ),
    ]
