# Generated by Django 4.2.16 on 2025-09-01 06:55

from django.db import migrations, models
import docscanner_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0011_alter_currencyrate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="purchase_defaults",
            field=models.JSONField(
                blank=True, default=docscanner_app.models._purchase_default
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sales_defaults",
            field=models.JSONField(
                blank=True, default=docscanner_app.models._sales_default
            ),
        ),
    ]
