# Generated by Django 4.2.16 on 2025-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0012_customuser_purchase_defaults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productautocomplete",
            name="preke_paslauga",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Preke_paslauga"
            ),
        ),
    ]
