# Generated by Django 4.2.16 on 2025-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0012_remove_apskaita5autocomplete_docscanner__user_id_d057bc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_islaidos_prekes_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Išlaidos prekės kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_islaidos_prekes_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Išlaidos prekės pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_klientai_iban",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Klientai IBAN"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_klientai_imones_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Klientai įmonės kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_klientai_kodas_programoje",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Klientai kodas programoje"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_klientai_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Klientai pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="apsk5_klientai_pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Klientai PVM kodas"
            ),
        ),
    ]
