# Generated by Django 4.2.16 on 2025-07-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0013_scanneddocument_apsk5_islaidos_prekes_kodas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_country",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_iban",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_is_person",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_vat_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="document_type_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="report_to_isaf",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_country",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_iban",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_is_person",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_vat_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="separate_vat",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="with_receipt",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="xml_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("centas", "Centas"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("vat_class", models.CharField(blank=True, max_length=50, null=True)),
                ("warehouse", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
            ],
        ),
    ]
