# Generated by Django 4.2.16 on 2025-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0013_productautocomplete_preke_paslauga"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="view_mode",
            field=models.CharField(
                choices=[("single", "Single-company"), ("multi", "Multi-company")],
                default="single",
                help_text="UI mode for documents: single or multi company.",
                max_length=16,
            ),
        ),
    ]
