# Generated by Django 4.2.16 on 2025-07-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0014_scanneddocument_buyer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="credits",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
