# Generated by Django 4.2.16 on 2025-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0014_customuser_view_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="glued_raw_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
