# Generated by Django 4.2.16 on 2025-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0015_alter_customuser_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Įmonės kodas"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Įmonės pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vat_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="PVM kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="pirkimas_pardavimas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pirkimas", "Pirkimas"),
                    ("pardavimas", "Pardavimas"),
                    ("nezinoma", "Nežinoma"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
