# Generated by Django 4.2.16 on 2025-09-21 11:43

from django.db import migrations, models
import docscanner_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0015_scanneddocument_glued_raw_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="extra_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="purchase_defaults",
            field=models.JSONField(
                blank=True, default=docscanner_app.models._purchase_default_list
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sales_defaults",
            field=models.JSONField(
                blank=True, default=docscanner_app.models._sales_default_list
            ),
        ),
    ]
