# Generated by Django 4.2.16 on 2025-09-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0016_customuser_extra_settings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("amount_subtotal", models.BigIntegerField(default=0)),
                ("amount_tax", models.BigIntegerField(default=0)),
                ("amount_total", models.BigIntegerField(default=0)),
                ("stripe_fee", models.BigIntegerField(default=0)),
                ("net_amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="eur", max_length=10)),
                ("credits_purchased", models.IntegerField(default=0)),
                (
                    "buyer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("buyer_address_json", models.JSONField(blank=True, default=dict)),
                ("payment_status", models.CharField(default="paid", max_length=32)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("receipt_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
