# Generated by Django 4.2.16 on 2025-07-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0016_customuser_company_code_customuser_company_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAutocomplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kodas_programoje",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Kliento kodas programoje",
                    ),
                ),
                (
                    "imones_kodas",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="Imonės kodas",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Pavadinimas"
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "ibans",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="IBANs (per kablelį, jei keli)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Klientas autocomplete įrašas",
                "verbose_name_plural": "Klientai autocomplete įrašai",
            },
        ),
        migrations.CreateModel(
            name="ProductAutocomplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Prekės kodas"
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Prekės barkodas"
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Prekės pavadinimas"
                    ),
                ),
                (
                    "prekes_tipas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Prekės tipas"
                    ),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Sandėlio kodas"
                    ),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sandėlio pavadinimas"
                    ),
                ),
                (
                    "objekto_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Objekto kodas"
                    ),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Objekto pavadinimas"
                    ),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Padalinio kodas"
                    ),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Padalinio pavadinimas"
                    ),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Mokesčio kodas"
                    ),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mokesčio pavadinimas"
                    ),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Atsakingo asmens kodas",
                    ),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Atsakingo asmens pavadinimas",
                    ),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Operacijos kodas"
                    ),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Operacijos pavadinimas",
                    ),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Išlaidų straipsnio kodas",
                    ),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Išlaidų straipsnio pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "pvm_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="PVM pavadinimas"
                    ),
                ),
                (
                    "tipo_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Tipo kodas"
                    ),
                ),
                (
                    "tipo_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tipo pavadinimas"
                    ),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Žurnalo kodas"
                    ),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Žurnalo pavadinimas"
                    ),
                ),
                (
                    "projekto_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Projekto kodas"
                    ),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Projekto pavadinimas"
                    ),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Projekto vadovo kodas"
                    ),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Projekto vadovo pavadinimas",
                    ),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Skyriaus kodas"
                    ),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Skyriaus pavadinimas"
                    ),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Partijos nr. kodas"
                    ),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Partijos nr. pavadinimas",
                    ),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Korespondencijos kodas",
                    ),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Korespondencijos pavadinimas",
                    ),
                ),
                (
                    "serijos_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Serijos kodas"
                    ),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Serijos pavadinimas"
                    ),
                ),
                (
                    "centro_kodas",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Centro kodas"
                    ),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Centro pavadinimas"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_autocomplete",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prekės autocomplete įrašas",
                "verbose_name_plural": "Prekės autocomplete įrašai",
            },
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="object_code",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="product_code",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="type",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="vat_class",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_islaidos_prekes_kodas",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_islaidos_prekes_pavadinimas",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_klientai_iban",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_klientai_imones_kodas",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_klientai_kodas_programoje",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_klientai_pavadinimas",
        ),
        migrations.RemoveField(
            model_name="scanneddocument",
            name="apsk5_klientai_pvm_kodas",
        ),
        migrations.AddField(
            model_name="lineitem",
            name="atsakingo_asmens_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Atsakingo asmens kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="atsakingo_asmens_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Atsakingo asmens pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="centro_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Centro kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="centro_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Centro pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="islaidu_straipsnio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Išlaidų straipsnio kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="islaidu_straipsnio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Išlaidų straipsnio pavadinimas",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="korespondencijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Korespondencijos kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="korespondencijos_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Korespondencijos pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="mokescio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Mokesčio kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="mokescio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mokesčio pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="objekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Objekto kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="objekto_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Objekto pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="operacijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Operacijos kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="operacijos_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Operacijos pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="padalinio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Padalinio kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="padalinio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Padalinio pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="partijos_nr_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Partijos nr. kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="partijos_nr_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Partijos nr. pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="prekes_barkodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Prekės barkodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="prekes_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Prekės kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="prekes_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Prekės pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="prekes_tipas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Prekės tipas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="projekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Projekto kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="projekto_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Projekto pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="projekto_vadovo_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Projekto vadovo kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="projekto_vadovo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Projekto vadovo pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="PVM kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="pvm_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="PVM pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="sandelio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Sandėlio kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="sandelio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Sandėlio pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="serijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Serijos kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="serijos_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Serijos pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="skyrio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Skyriaus kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="skyrio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Skyriaus pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="tipo_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Tipo kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="tipo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Tipo pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="zurnalo_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Žurnalo kodas"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="zurnalo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Žurnalo pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="atsakingo_asmens_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Atsakingo asmens kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="atsakingo_asmens_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Atsakingo asmens pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="centro_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Centro kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="centro_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Centro pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="islaidu_straipsnio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Išlaidų straipsnio kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="islaidu_straipsnio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Išlaidų straipsnio pavadinimas",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="korespondencijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Korespondencijos kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="korespondencijos_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Korespondencijos pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="mokescio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Mokesčio kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="mokescio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mokesčio pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="objekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Objekto kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="objekto_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Objekto pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="operacijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Operacijos kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="operacijos_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Operacijos pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="padalinio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Padalinio kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="padalinio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Padalinio pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="partijos_nr_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Partijos nr. kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="partijos_nr_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Partijos nr. pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="prekes_barkodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Prekės barkodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="prekes_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Prekės kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="prekes_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Prekės pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="prekes_tipas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Prekės tipas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="projekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Projekto kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="projekto_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Projekto pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="projekto_vadovo_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Projekto vadovo kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="projekto_vadovo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Projekto vadovo pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="PVM kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="pvm_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="PVM pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="sandelio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Sandėlio kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="sandelio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Sandėlio pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="serijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Serijos kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="serijos_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Serijos pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="skyrio_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Skyriaus kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="skyrio_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Skyriaus pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="tipo_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Tipo kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="tipo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Tipo pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="zurnalo_kodas",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Žurnalo kodas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="zurnalo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Žurnalo pavadinimas"
            ),
        ),
        migrations.DeleteModel(
            name="Apskaita5Autocomplete",
        ),
        migrations.AddIndex(
            model_name="productautocomplete",
            index=models.Index(
                fields=["user", "prekes_kodas"], name="docscanner__user_id_4c0dd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientautocomplete",
            index=models.Index(
                fields=["user", "imones_kodas"], name="docscanner__user_id_f31e32_idx"
            ),
        ),
    ]
