# Generated by Django 4.2.16 on 2025-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0017_clientautocomplete_productautocomplete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="scan_type",
            field=models.CharField(
                choices=[("sumiskai", "Sumiškai"), ("detaliai", "Detaliai")],
                default="sumiskai",
                max_length=32,
            ),
        ),
    ]
