# Generated by Django 4.2.16 on 2025-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0018_scanneddocument_scan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneddocument",
            name="buyer_country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="currency",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="seller_country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
