# Generated by Django 4.2.16 on 2025-10-05 14:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("docscanner_app", "0018_guidecategorypage_guideindexpage_guidepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guideindexpage",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="guidepage",
            name="summary",
        ),
        migrations.AddField(
            model_name="guidecategorypage",
            name="cat_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="guidecategorypage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="author_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("code", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "image",
                            ]
                        },
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                },
            ),
        ),
    ]
