# Generated by Django 4.2.16 on 2025-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0019_alter_scanneddocument_buyer_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_country_iso",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_id_programoje",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_country_iso",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_id_programoje",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
