# Generated by Django 4.2.16 on 2025-10-08 08:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0019_remove_guideindexpage_intro_remove_guidepage_summary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("youtube", 3),
                    ("code", 4),
                    ("quote", 5),
                    ("table", 10),
                    ("divider", 11),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "image",
                                "blockquote",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Вставь YouTube ссылку"},
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Вставь кодовый блок"},
                    ),
                    5: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: ("wagtail.blocks.StreamBlock", [[("row", 8)]], {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("caption", 6), ("data", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"label": "Space line"},
                    ),
                },
            ),
        ),
    ]
