# Generated by Django 4.2.16 on 2025-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0020_scanneddocument_buyer_country_iso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneddocument",
            name="vat_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
