# Generated by Django 4.2.16 on 2025-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0020_alter_guidepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidecategorypage",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
