# Generated by Django 4.2.16 on 2025-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0021_alter_scanneddocument_vat_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVMKlasifikatoriai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodas", models.CharField(max_length=16, unique=True)),
                ("aprasymas", models.TextField()),
                ("tarifas", models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
