# Generated by Django 4.2.16 on 2025-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0022_pvmklasifikatoriai"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="val_ar_sutapo",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="val_subtotal_match",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="val_total_match",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="val_vat_match",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
