# Generated by Django 4.2.16 on 2025-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0022_guides_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="math_validation_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="ready_for_export",
            field=models.BooleanField(default=False),
        ),
    ]
