# Generated by Django 4.2.16 on 2025-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0023_scanneddocument_val_ar_sutapo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientautocomplete",
            name="ibans",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="IBANs (per kablelį, jei keli)",
            ),
        ),
        migrations.AlterField(
            model_name="clientautocomplete",
            name="imones_kodas",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="Imonės kodas",
            ),
        ),
        migrations.AlterField(
            model_name="clientautocomplete",
            name="kodas_programoje",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Kliento kodas programoje",
            ),
        ),
        migrations.AlterField(
            model_name="clientautocomplete",
            name="pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="clientautocomplete",
            name="pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="PVM kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="atsakingo_asmens_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Atsakingo asmens kodas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="atsakingo_asmens_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Atsakingo asmens pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="centro_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Centro kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="centro_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Centro pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="islaidu_straipsnio_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Išlaidų straipsnio kodas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="islaidu_straipsnio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Išlaidų straipsnio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="korespondencijos_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Korespondencijos kodas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="korespondencijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Korespondencijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="mokescio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Mokesčio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="mokescio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Mokesčio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="objekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Objekto kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="objekto_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Objekto pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="operacijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Operacijos kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="operacijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Operacijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="padalinio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Padalinio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="padalinio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Padalinio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="partijos_nr_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Partijos nr. kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="partijos_nr_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Partijos nr. pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="projekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Projekto kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="projekto_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Projekto pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="projekto_vadovo_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Projekto vadovo kodas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="projekto_vadovo_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Projekto vadovo pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="PVM kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="pvm_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PVM pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="sandelio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Sandėlio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="sandelio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sandėlio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="serijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Serijos kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="serijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Serijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="skyrio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Skyriaus kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="skyrio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Skyriaus pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="tipo_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Tipo kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="tipo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="zurnalo_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Žurnalo kodas"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="zurnalo_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Žurnalo pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="atsakingo_asmens_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Atsakingo asmens kodas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="atsakingo_asmens_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Atsakingo asmens pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="centro_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Centro kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="centro_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Centro pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="islaidu_straipsnio_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Išlaidų straipsnio kodas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="islaidu_straipsnio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Išlaidų straipsnio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="korespondencijos_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Korespondencijos kodas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="korespondencijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Korespondencijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="mokescio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Mokesčio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="mokescio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Mokesčio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="objekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Objekto kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="objekto_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Objekto pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="operacijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Operacijos kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="operacijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Operacijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="padalinio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Padalinio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="padalinio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Padalinio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="partijos_nr_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Partijos nr. kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="partijos_nr_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Partijos nr. pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="prekes_barkodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės barkodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="prekes_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="prekes_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prekės pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="prekes_tipas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės tipas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="projekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Projekto kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="projekto_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Projekto pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="projekto_vadovo_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Projekto vadovo kodas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="projekto_vadovo_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Projekto vadovo pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="PVM kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="pvm_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PVM pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="sandelio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Sandėlio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="sandelio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sandėlio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="serijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Serijos kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="serijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Serijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="skyrio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Skyriaus kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="skyrio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Skyriaus pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="tipo_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Tipo kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="tipo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="zurnalo_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Žurnalo kodas"
            ),
        ),
        migrations.AlterField(
            model_name="productautocomplete",
            name="zurnalo_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Žurnalo pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="atsakingo_asmens_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Atsakingo asmens kodas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="atsakingo_asmens_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Atsakingo asmens pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="centro_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Centro kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="centro_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Centro pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="islaidu_straipsnio_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Išlaidų straipsnio kodas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="islaidu_straipsnio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Išlaidų straipsnio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="korespondencijos_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Korespondencijos kodas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="korespondencijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Korespondencijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="mokescio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Mokesčio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="mokescio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Mokesčio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="objekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Objekto kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="objekto_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Objekto pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="operacijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Operacijos kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="operacijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Operacijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="padalinio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Padalinio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="padalinio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Padalinio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="partijos_nr_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Partijos nr. kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="partijos_nr_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Partijos nr. pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="prekes_barkodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės barkodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="prekes_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="prekes_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prekės pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="prekes_tipas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Prekės tipas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="projekto_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Projekto kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="projekto_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Projekto pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="projekto_vadovo_kodas",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Projekto vadovo kodas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="projekto_vadovo_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Projekto vadovo pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="pvm_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="PVM kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="pvm_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PVM pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="sandelio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Sandėlio kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="sandelio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sandėlio pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="serijos_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Serijos kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="serijos_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Serijos pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="skyrio_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Skyriaus kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="skyrio_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Skyriaus pavadinimas",
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="tipo_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Tipo kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="tipo_pavadinimas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo pavadinimas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="zurnalo_kodas",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Žurnalo kodas"
            ),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="zurnalo_pavadinimas",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Žurnalo pavadinimas",
            ),
        ),
    ]
