# Generated by Django 4.2.16 on 2025-11-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0023_scanneddocument_math_validation_passed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneddocument",
            name="math_validation_passed",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="ready_for_export",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
