# Generated by Django 4.2.16 on 2025-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("docscanner_app", "0024_alter_clientautocomplete_ibans_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="clientautocomplete",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientautocomplete",
            name="country_iso",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Įmonės adresas"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_country_iso",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Įmonės šalis"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_iban",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Įmonės IBAN"
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="discount_with_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="discount_wo_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
