# Generated by Django 4.2.16 on 2025-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0024_alter_scanneddocument_math_validation_passed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
