# Generated by Django 4.2.16 on 2025-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0025_homepage_clientautocomplete_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="invoice_discount_with_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="invoice_discount_wo_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
