# Generated by Django 4.2.16 on 2025-11-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0026_alter_lineitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=20, null=True
            ),
        ),
    ]
