# Generated by Django 4.2.16 on 2025-11-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0028_alter_lineitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_name_normalized",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_name_normalized",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["user", "seller_name_normalized"], name="idx_user_seller_norm"
            ),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["user", "buyer_name_normalized"], name="idx_user_buyer_norm"
            ),
        ),
    ]
