# Generated by Django 4.2.16 on 2025-11-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0029_scanneddocument_buyer_name_normalized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_vat_val",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_vat_val",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
