# Generated by Django 4.2.16 on 2025-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0030_scanneddocument_buyer_vat_val_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lineitem_rules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="view_mode",
            field=models.CharField(
                choices=[("single", "Single-company"), ("multi", "Multi-company")],
                default="multi",
                help_text="UI mode for documents: single or multi company.",
                max_length=16,
            ),
        ),
    ]
