# Generated by Django 4.2.16 on 2025-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0031_customuser_lineitem_rules_alter_customuser_view_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dineta_settings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
