# Generated by Django 4.2.16 on 2025-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0033_customuser_rivile_erp_extra_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rivile_gama_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
