# Generated by Django 4.2.16 on 2025-12-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0034_customuser_rivile_gama_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="agnum_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customuser",
            name="butent_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customuser",
            name="centas_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customuser",
            name="finvalda_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
