# Generated by Django 4.2.16 on 2025-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0035_customuser_agnum_extra_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="doc_96_str",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
