# Generated by Django 4.2.16 on 2025-12-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0038_alter_customuser_default_accounting_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="site_pro_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
