# Generated by Django 4.2.16 on 2025-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0039_customuser_site_pro_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="optimum_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="dineta_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
