# Generated by Django 4.2.16 on 2025-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0040_customuser_optimum_settings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pragma3_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
