# Generated by Django 4.2.16 on 2025-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0041_customuser_pragma3_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
