# Generated by Django 4.2.16 on 2025-12-27 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docscanner_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0042_customuser_mobile_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hešas nuo pilno mobilio rakto",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "key_last4",
                    models.CharField(
                        db_index=True,
                        help_text="Paskutiniai 4 rakto simboliai (rodymui nustatymuose)",
                        max_length=4,
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mobile_key",
        ),
        migrations.CreateModel(
            name="MobileInboxDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        upload_to=docscanner_app.models.mobile_document_upload_to
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="Конкретный моб. ключ, через который пришёл файл",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="docscanner_app.mobileaccesskey",
                    ),
                ),
                (
                    "processed_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если не NULL – этот файл уже использован для основного Document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_mobile_documents",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_inbox_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mobileaccesskey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobile_access_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
