# Generated by Django 4.2.16 on 2025-12-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0043_mobileaccesskey_remove_customuser_mobile_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="is_processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="preview_url",
            field=models.URLField(
                blank=True,
                help_text="Pilnas URL, kurį WEB gali naudoti peržiūrai (PDF/preview)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mobileinboxdocument",
            name="processed_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_mobile_documents",
                to="docscanner_app.scanneddocument",
            ),
        ),
    ]
