# Generated by Django 4.2.16 on 2025-12-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0044_mobileinboxdocument_is_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="dok_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
    ]
