# Generated by Django 4.2.16 on 2025-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0045_payments_dok_number"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scanneddocument",
            name="docscanner__user_id_bc3664_idx",
        ),
        migrations.RemoveIndex(
            model_name="scanneddocument",
            name="docscanner__uploade_7257ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="scanneddocument",
            name="docscanner__seller__2331cc_idx",
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="idx_user_uploaded_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["user", "status", "-uploaded_at"],
                name="idx_user_status_uploaded",
            ),
        ),
    ]
