# Generated by Django 4.2.16 on 2026-01-05 15:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0046_remove_scanneddocument_docscanner__user_id_bc3664_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkedUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_size", models.BigIntegerField()),
                ("chunk_size", models.IntegerField()),
                ("total_chunks", models.IntegerField()),
                ("received", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "uploading"),
                            ("complete", "complete"),
                            ("failed", "failed"),
                        ],
                        default="uploading",
                        max_length=16,
                    ),
                ),
                ("tmp_path", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(db_index=True, default="sumiskai", max_length=32),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("uploading", "uploading"),
                            ("credit_check", "credit_check"),
                            ("queued", "queued"),
                            ("processing", "processing"),
                            ("done", "done"),
                            ("blocked", "blocked"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="uploading",
                        max_length=32,
                    ),
                ),
                ("client_total_files", models.PositiveIntegerField(default=0)),
                ("uploaded_files", models.PositiveIntegerField(default=0)),
                ("uploaded_bytes", models.BigIntegerField(default=0)),
                ("expected_items", models.PositiveIntegerField(default=0)),
                ("actual_items", models.PositiveIntegerField(default=0)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("done_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("pending_archives", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reserved_credits",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reserved_items", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="credits_reserved",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="counted_in_session",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="is_archive_container",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="docscanner_app.scanneddocument",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="upload_batch_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="uploaded_size_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scanneddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Tikrinami"),
                    ("processing", "Vykdomi"),
                    ("completed", "Atlikti (Neeksportuoti)"),
                    ("rejected", "Atmesti"),
                    ("exported", "Atlikti (Eksportuoti)"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
        # Сначала добавляем user в UploadSession
        migrations.AddField(
            model_name="uploadsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Потом добавляем upload_session в ScannedDocument
        migrations.AddField(
            model_name="scanneddocument",
            name="upload_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="docscanner_app.uploadsession",
            ),
        ),
        # Теперь можно создавать индексы на ScannedDocument
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["upload_session"], name="docscanner__upload__42cbfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanneddocument",
            index=models.Index(
                fields=["parent_document"], name="docscanner__parent__e37fb4_idx"
            ),
        ),
        # ChunkedUpload зависит от UploadSession
        migrations.AddField(
            model_name="chunkedupload",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunked_uploads",
                to="docscanner_app.uploadsession",
            ),
        ),
        migrations.AddField(
            model_name="chunkedupload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunked_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Индексы для UploadSession и ChunkedUpload
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["user", "stage"], name="docscanner__user_id_9f8016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadsession",
            index=models.Index(
                fields=["created_at"], name="docscanner__created_86169c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunkedupload",
            index=models.Index(
                fields=["user", "status"], name="docscanner__user_id_988d81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunkedupload",
            index=models.Index(
                fields=["session", "status"], name="docscanner__session_c8523e_idx"
            ),
        ),
    ]