# Generated by Django 4.2.16 on 2026-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0047_chunkedupload_uploadsession_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadsession",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="archive_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("zip", "ZIP"),
                    ("rar", "RAR"),
                    ("7z", "7Z"),
                    ("tar", "TAR"),
                    ("tar.gz", "TAR.GZ"),
                    ("tar.bz2", "TAR.BZ2"),
                    ("tar.xz", "TAR.XZ"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
