# Generated by Django 4.2.16 on 2026-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0048_alter_uploadsession_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsession",
            name="archive_format",
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="archive_formats",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
