# Generated by Django 4.2.16 on 2026-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0049_remove_uploadsession_archive_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pswd_code_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Kodo išsiuntimo laikas"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pswd_reset_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Neteisingų bandymų skaičius"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pswd_reset_code",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="Slaptažodžio atkūrimo kodas",
            ),
        ),
    ]
