# Generated by Django 4.2.16 on 2026-02-09 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0051_customuser_dineta_extra_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="optimum_api_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="optimum_last_try_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="APIExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(choices=[("optimum", "Optimum")], max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial_success", "Partial Success"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice_type", models.CharField(max_length=30)),
                ("invoice_status", models.CharField(max_length=10)),
                ("invoice_result", models.IntegerField(blank=True, null=True)),
                ("invoice_error", models.TextField(blank=True, default="")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_export_logs",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_export_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIExportArticleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_name", models.CharField(max_length=255)),
                (
                    "article_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("status", models.CharField(max_length=10)),
                ("result", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "export_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_logs",
                        to="docscanner_app.apiexportlog",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="apiexportlog",
            index=models.Index(
                fields=["document", "program", "-created_at"],
                name="docscanner__documen_504cef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiexportlog",
            index=models.Index(
                fields=["user", "program", "-created_at"],
                name="docscanner__user_id_a53455_idx",
            ),
        ),
    ]
