# Generated by Django 4.2.16 on 2026-02-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0052_scanneddocument_optimum_api_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(choices=[("optimum", "Optimum")], max_length=50),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("total_documents", models.IntegerField(default=0)),
                ("processed_documents", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("partial_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "documents",
                    models.ManyToManyField(
                        related_name="export_sessions",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="apiexportlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="export_logs",
                to="docscanner_app.exportsession",
            ),
        ),
        migrations.AddIndex(
            model_name="exportsession",
            index=models.Index(
                fields=["user", "stage", "-created_at"],
                name="docscanner__user_id_620e01_idx",
            ),
        ),
    ]
