# Generated by Django 4.2.16 on 2026-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0053_exportsession_apiexportlog_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiexportarticlelog",
            name="full_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apiexportlog",
            name="full_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apiexportlog",
            name="partner_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apiexportlog",
            name="partner_status",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="dineta_api_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="dineta_last_try_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apiexportlog",
            name="program",
            field=models.CharField(
                choices=[("optimum", "Optimum"), ("dineta", "Dineta")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="exportsession",
            name="program",
            field=models.CharField(
                choices=[("optimum", "Optimum"), ("dineta", "Dineta")], max_length=50
            ),
        ),
    ]
