# Generated by Django 4.2.16 on 2026-02-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0055_alter_customuser_default_accounting_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pragma4_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
