# Generated by Django 4.2.16 on 2026-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0056_customuser_pragma4_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiexportarticlelog",
            name="message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="apiexportlog",
            name="message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="apiexportlog",
            name="partner_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
