# Generated by Django 4.2.16 on 2026-02-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0057_apiexportarticlelog_message_apiexportlog_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_inbox_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=15, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="sender_subject",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="source",
            field=models.CharField(
                choices=[("mob", "Mob. programėlė"), ("email", "El. paštas")],
                db_index=True,
                default="mob",
                max_length=10,
            ),
        ),
    ]
