# Generated by Django 4.2.16 on 2026-02-22 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0058_customuser_email_inbox_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Kliento pavadinimas"
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        max_length=255, verbose_name="Aplanko pavadinimas"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "folder_name")},
            },
        ),
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="remote_file_id",
            field=models.CharField(
                blank=True,
                help_text="Failo ID debesyje (reikalingas pervadinimui)",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="rename_status",
            field=models.CharField(
                choices=[
                    ("na", "N/A"),
                    ("pending", "Laukia"),
                    ("done", "Atlikta"),
                    ("failed", "Klaida"),
                ],
                default="na",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mobileinboxdocument",
            name="source",
            field=models.CharField(
                choices=[("mob", "Mob. programėlė"), ("email", "El. paštas")],
                db_index=True,
                default="mob",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CloudConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_drive", "Google Drive"),
                            ("dropbox", "Dropbox"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("dropbox_cursor", models.TextField(blank=True, null=True)),
                (
                    "gdrive_channel_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gdrive_channel_expiration",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "account_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.AddField(
            model_name="mobileinboxdocument",
            name="cloud_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbox_documents",
                to="docscanner_app.cloudclient",
            ),
        ),
        migrations.CreateModel(
            name="CloudClientFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_folder_id", models.CharField(max_length=512)),
                ("is_shared", models.BooleanField(default=False)),
                ("shared_with_emails", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cloud_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_folders",
                        to="docscanner_app.cloudclient",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_folders",
                        to="docscanner_app.cloudconnection",
                    ),
                ),
            ],
            options={
                "unique_together": {("cloud_client", "connection")},
            },
        ),
    ]
