# Generated by Django 4.2.16 on 2026-02-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0059_cloudclient_mobileinboxdocument_remote_file_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Registracijos IP"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("stekas", "Stekas Plius"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
