# Generated by Django 4.2.16 on 2026-03-01 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import docscanner_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0060_customuser_registration_ip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Pavadinimas")),
                (
                    "name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "vat_code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Adresas"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Šalis"
                    ),
                ),
                (
                    "country_iso",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Šalies ISO"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Telefonas"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="El. paštas",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Banko pavadinimas",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="IBAN"
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="SWIFT/BIC"
                    ),
                ),
                (
                    "is_person",
                    models.BooleanField(default=False, verbose_name="Fizinis asmuo"),
                ),
                (
                    "default_role",
                    models.CharField(
                        choices=[
                            ("buyer", "Pirkėjas"),
                            ("seller", "Pardavėjas"),
                            ("both", "Abu"),
                        ],
                        default="buyer",
                        max_length=10,
                    ),
                ),
                (
                    "id_programoje",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="ID programoje",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counterparties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counterparty",
                "verbose_name_plural": "Counterparties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("isankstine", "Išankstinė sąskaita faktūra"),
                            ("pvm_saskaita", "PVM sąskaita faktūra"),
                            ("saskaita", "Sąskaita faktūra"),
                            ("kreditine", "Kreditinė sąskaita faktūra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Juodraštis"),
                            ("issued", "Išrašyta"),
                            ("sent", "Išsiųsta"),
                            ("paid", "Apmokėta"),
                            ("overdue", "Vėluojanti"),
                            ("cancelled", "Atšaukta"),
                            ("exported", "Eksportuota"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "document_series",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Serija"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Numeris"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Sąskaitos data"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Mokėti iki"),
                ),
                (
                    "operation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Operacijos data"
                    ),
                ),
                (
                    "seller_id_programoje",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "seller_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "seller_vat_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seller_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_country",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seller_country_iso",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "seller_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seller_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "seller_bank_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_iban",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_swift",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("seller_is_person", models.BooleanField(blank=True, null=True)),
                (
                    "seller_vat_val",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "buyer_id_programoje",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "buyer_vat_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "buyer_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_country",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "buyer_country_iso",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "buyer_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "buyer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "buyer_bank_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_iban",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_swift",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("buyer_is_person", models.BooleanField(blank=True, null=True)),
                (
                    "buyer_vat_val",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("currency", models.CharField(default="EUR", max_length=20)),
                (
                    "pvm_tipas",
                    models.CharField(
                        choices=[("taikoma", "Taikoma"), ("netaikoma", "Netaikoma")],
                        default="taikoma",
                        max_length=20,
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=21,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "amount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "invoice_discount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "invoice_discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Pristatymo mokestis",
                    ),
                ),
                ("separate_vat", models.BooleanField(blank=True, null=True)),
                ("doc_96_str", models.BooleanField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "document_type_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "pirkimas_pardavimas",
                    models.CharField(
                        choices=[
                            ("pirkimas", "Pirkimas"),
                            ("pardavimas", "Pardavimas"),
                        ],
                        default="pardavimas",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("report_to_isaf", models.BooleanField(blank=True, null=True)),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės kodas",
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės barkodas",
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Prekės pavadinimas",
                    ),
                ),
                (
                    "prekes_tipas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės tipas",
                    ),
                ),
                (
                    "preke_paslauga",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="Preke_paslauga",
                    ),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Sandėlio kodas",
                    ),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Sandėlio pavadinimas",
                    ),
                ),
                (
                    "objekto_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Objekto kodas",
                    ),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Objekto pavadinimas",
                    ),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Padalinio kodas",
                    ),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Padalinio pavadinimas",
                    ),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Mokesčio kodas",
                    ),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Mokesčio pavadinimas",
                    ),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Atsakingo asmens kodas",
                    ),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Atsakingo asmens pavadinimas",
                    ),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Operacijos kodas",
                    ),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Operacijos pavadinimas",
                    ),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Išlaidų straipsnio kodas",
                    ),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Išlaidų straipsnio pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "pvm_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="PVM pavadinimas",
                    ),
                ),
                (
                    "tipo_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Tipo kodas",
                    ),
                ),
                (
                    "tipo_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Tipo pavadinimas",
                    ),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Žurnalo kodas",
                    ),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Žurnalo pavadinimas",
                    ),
                ),
                (
                    "projekto_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Projekto kodas",
                    ),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Projekto pavadinimas",
                    ),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Projekto vadovo kodas",
                    ),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Projekto vadovo pavadinimas",
                    ),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Skyriaus kodas",
                    ),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Skyriaus pavadinimas",
                    ),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Partijos nr. kodas",
                    ),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Partijos nr. pavadinimas",
                    ),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Korespondencijos kodas",
                    ),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Korespondencijos pavadinimas",
                    ),
                ),
                (
                    "serijos_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Serijos kodas",
                    ),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Serijos pavadinimas",
                    ),
                ),
                (
                    "centro_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Centro kodas",
                    ),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Centro pavadinimas",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=docscanner_app.models.invoice_pdf_path,
                        verbose_name="PDF failas",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Išsiųsta"
                    ),
                ),
                (
                    "sent_to_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Siųsta kam",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Apmokėta"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atšaukta"
                    ),
                ),
                (
                    "public_link_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Ar pirkėjas gali peržiūrėti sąskaitą per uuid nuorodą",
                        verbose_name="Viešas peržiūros nuoroda",
                    ),
                ),
                (
                    "optimum_api_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("optimum_last_try_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dineta_api_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("dineta_last_try_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_as_buyer",
                        to="docscanner_app.counterparty",
                    ),
                ),
                (
                    "seller_counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_as_seller",
                        to="docscanner_app.counterparty",
                    ),
                ),
                (
                    "source_invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Išankstinė, iš kurios sukurta ši PVM SF",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_invoices",
                        to="docscanner_app.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Pardavėjo pavadinimas",
                    ),
                ),
                (
                    "seller_company_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "seller_vat_code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "seller_address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Adresas"
                    ),
                ),
                (
                    "seller_phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Telefonas"
                    ),
                ),
                (
                    "seller_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="El. paštas",
                    ),
                ),
                (
                    "seller_bank_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Banko pavadinimas",
                    ),
                ),
                (
                    "seller_iban",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="IBAN"
                    ),
                ),
                (
                    "seller_swift",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="SWIFT/BIC"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=docscanner_app.models.invoice_logo_path,
                        verbose_name="Logotipas",
                    ),
                ),
                (
                    "isankstine_series",
                    models.CharField(
                        blank=True,
                        default="ISF",
                        max_length=20,
                        verbose_name="Išankstinės serija",
                    ),
                ),
                (
                    "isankstine_next_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Išankstinės kitas Nr."
                    ),
                ),
                (
                    "pvm_sf_series",
                    models.CharField(
                        blank=True,
                        default="SF",
                        max_length=20,
                        verbose_name="PVM SF serija",
                    ),
                ),
                (
                    "pvm_sf_next_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="PVM SF kitas Nr."
                    ),
                ),
                (
                    "sf_series",
                    models.CharField(
                        blank=True,
                        default="SF",
                        max_length=20,
                        verbose_name="SF serija",
                    ),
                ),
                (
                    "sf_next_number",
                    models.PositiveIntegerField(default=1, verbose_name="SF kitas Nr."),
                ),
                (
                    "kreditine_series",
                    models.CharField(
                        blank=True,
                        default="KR",
                        max_length=20,
                        verbose_name="Kreditinės serija",
                    ),
                ),
                (
                    "kreditine_next_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Kreditinės kitas Nr."
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="EUR", max_length=10, verbose_name="Numatyta valiuta"
                    ),
                ),
                (
                    "default_vat_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=21,
                        max_digits=5,
                        verbose_name="Numatytas PVM %",
                    ),
                ),
                (
                    "default_payment_days",
                    models.PositiveIntegerField(
                        default=14, verbose_name="Mokėjimo terminas (dienomis)"
                    ),
                ),
                (
                    "number_padding",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Pvz. 3 → 001, 4 → 0001",
                        verbose_name="Numerio ilgis (su nuliais)",
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True,
                        default="Sąskaita faktūra Nr. {series}{number}",
                        max_length=255,
                    ),
                ),
                (
                    "email_body_template",
                    models.TextField(
                        blank=True,
                        default="Laba diena,\n\nSiunčiame sąskaitą faktūrą Nr. {series}{number}.\nMokėti iki: {due_date}.\nSuma: {total} {currency}.\n\nPagarbiai,\n{seller_name}",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Settings",
                "verbose_name_plural": "Invoice Settings",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės kodas",
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės barkodas",
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Prekės pavadinimas",
                    ),
                ),
                (
                    "prekes_tipas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės tipas",
                    ),
                ),
                (
                    "preke_paslauga",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="Preke_paslauga",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="vnt",
                        max_length=50,
                        verbose_name="Mato vnt.",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Kaina",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Suma be PVM",
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="PVM suma",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="PVM %",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Suma su PVM",
                    ),
                ),
                (
                    "discount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Sandėlio kodas",
                    ),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Sandėlio pavadinimas",
                    ),
                ),
                (
                    "objekto_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Objekto kodas",
                    ),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Objekto pavadinimas",
                    ),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Padalinio kodas",
                    ),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Padalinio pavadinimas",
                    ),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Mokesčio kodas",
                    ),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Mokesčio pavadinimas",
                    ),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Atsakingo asmens kodas",
                    ),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Atsakingo asmens pavadinimas",
                    ),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Operacijos kodas",
                    ),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Operacijos pavadinimas",
                    ),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Išlaidų straipsnio kodas",
                    ),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Išlaidų straipsnio pavadinimas",
                    ),
                ),
                (
                    "pvm_kodas",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "pvm_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="PVM pavadinimas",
                    ),
                ),
                (
                    "tipo_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Tipo kodas",
                    ),
                ),
                (
                    "tipo_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Tipo pavadinimas",
                    ),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Žurnalo kodas",
                    ),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Žurnalo pavadinimas",
                    ),
                ),
                (
                    "projekto_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Projekto kodas",
                    ),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Projekto pavadinimas",
                    ),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Projekto vadovo kodas",
                    ),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Projekto vadovo pavadinimas",
                    ),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Skyriaus kodas",
                    ),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Skyriaus pavadinimas",
                    ),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Partijos nr. kodas",
                    ),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Partijos nr. pavadinimas",
                    ),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Korespondencijos kodas",
                    ),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Korespondencijos pavadinimas",
                    ),
                ),
                (
                    "serijos_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Serijos kodas",
                    ),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Serijos pavadinimas",
                    ),
                ),
                (
                    "centro_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Centro kodas",
                    ),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Centro pavadinimas",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="docscanner_app.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["invoice"], name="idx_invline_invoice")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_inv_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="idx_inv_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "invoice_type", "-created_at"], name="idx_inv_user_type"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["uuid"], name="idx_inv_uuid"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "buyer_name_normalized"], name="idx_inv_buyer_norm"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["due_date"], name="idx_inv_due_date"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["source_invoice"], name="idx_inv_source"),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(
                fields=["user", "name_normalized"], name="idx_cp_user_name_norm"
            ),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(
                fields=["user", "company_code"], name="idx_cp_user_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_code", ""), _negated=True),
                fields=("user", "company_code"),
                name="unique_user_company_code",
            ),
        ),
    ]
