# Generated by Django 4.2.16 on 2026-03-02 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0061_counterparty_invoice_invoicesettings_invoicelineitem_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicesettings",
            name="isankstine_next_number",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="isankstine_series",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="kreditine_next_number",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="kreditine_series",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="number_padding",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="pvm_sf_next_number",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="pvm_sf_series",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="sf_next_number",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="sf_series",
        ),
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Короткий код: vnt, kg, val...", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Полное название", max_length=100
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "unique_together": {("user", "code")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("isankstine", "Išankstinė SF"),
                            ("pvm_saskaita", "PVM SF"),
                            ("saskaita", "SF"),
                            ("kreditine", "Kreditinė SF"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Серийный префикс, напр. AA, BB, ISF", max_length=20
                    ),
                ),
                ("next_number", models.PositiveIntegerField(default=1)),
                (
                    "padding",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Кол-во цифр с нулями: 3 → 001, 4 → 0001"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Серия по умолчанию для данного типа"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Invoice series",
                "ordering": ["invoice_type", "-is_default", "prefix"],
                "unique_together": {("user", "prefix")},
            },
        ),
    ]
