# Generated by Django 4.2.16 on 2026-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0062_remove_invoicesettings_isankstine_next_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementunit",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Numatytasis matavimo vienetas"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceseries",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invoiceseries",
            name="padding",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="invoiceseries",
            name="prefix",
            field=models.CharField(max_length=20),
        ),
    ]
