# Generated by Django 4.2.16 on 2026-03-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0063_measurementunit_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterparty",
            name="delivery_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="extra_info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
