# Generated by Django 4.2.16 on 2026-03-03 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0064_counterparty_delivery_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preke_paslauga",
                    models.CharField(
                        choices=[("preke", "Prekė"), ("paslauga", "Paslauga")],
                        default="preke",
                        max_length=12,
                        verbose_name="Tipas",
                    ),
                ),
                (
                    "pavadinimas",
                    models.CharField(max_length=255, verbose_name="Pavadinimas"),
                ),
                (
                    "kodas",
                    models.CharField(max_length=128, verbose_name="Prekės kodas"),
                ),
                (
                    "barkodas",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Barkodas"
                    ),
                ),
                (
                    "pardavimo_kaina",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Pardavimo kaina (be PVM)",
                    ),
                ),
                (
                    "pvm_procentas",
                    models.DecimalField(
                        decimal_places=2, default=21, max_digits=5, verbose_name="PVM %"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="docscanner_app.measurementunit",
                        verbose_name="Mato vienetas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["pavadinimas"],
                "indexes": [
                    models.Index(fields=["user", "kodas"], name="idx_prod_user_kodas"),
                    models.Index(
                        fields=["user", "pavadinimas"], name="idx_prod_user_pav"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("user", "kodas"), name="unique_user_product_kodas"
            ),
        ),
    ]
