# Generated by Django 4.2.16 on 2026-03-03 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0065_product_product_unique_user_product_kodas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pvm_procentas",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="PVM %",
            ),
        ),
    ]
