# Generated by Django 4.2.16 on 2026-03-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0066_alter_product_pvm_procentas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="pvm_pavadinimas",
        ),
        migrations.AddField(
            model_name="invoice",
            name="exported",
            field=models.BooleanField(default=False, verbose_name="Eksportuota"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exported_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Eksportavimo data"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Juodraštis"),
                    ("issued", "Išrašyta"),
                    ("sent", "Išsiųsta"),
                    ("paid", "Apmokėta"),
                    ("cancelled", "Atšaukta"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
