# Generated by Django 4.2.16 on 2026-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0067_remove_invoice_pvm_pavadinimas_invoice_exported_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="issued_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="received_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
