# Generated by Django 4.2.16 on 2026-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0068_invoice_issued_by_invoice_received_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="buyer_delivery_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="buyer_extra_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_extra_info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
