# Generated by Django 6.0.3 on 2026-03-10 07:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0069_invoice_buyer_delivery_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("isankstine", "Išankstinė sąskaita faktūra"),
                            ("pvm_saskaita", "PVM sąskaita faktūra"),
                            ("saskaita", "Sąskaita faktūra"),
                            ("kreditine", "Kreditinė sąskaita faktūra"),
                        ],
                        default="pvm_saskaita",
                        max_length=20,
                    ),
                ),
                (
                    "document_series",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Serija"
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=20)),
                (
                    "pvm_tipas",
                    models.CharField(
                        choices=[("taikoma", "Taikoma"), ("netaikoma", "Netaikoma")],
                        default="taikoma",
                        max_length=20,
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("21.00"),
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "order_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("public_link_enabled", models.BooleanField(default=True)),
                ("start_date", models.DateField(verbose_name="Начать с")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Остановить после"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Каждый день"),
                            ("weekly", "Каждую неделю"),
                            ("monthly", "Каждый месяц"),
                            ("quarterly", "Каждый квартал"),
                            ("yearly", "Каждый год"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Используется для weekly",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Используется для monthly/quarterly/yearly",
                        null=True,
                    ),
                ),
                (
                    "issue_time",
                    models.TimeField(
                        blank=True,
                        help_text="Во сколько создавать/отправлять",
                        null=True,
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(default="Europe/Vilnius", max_length=64),
                ),
                ("payment_term_days", models.PositiveIntegerField(default=0)),
                ("auto_issue", models.BooleanField(default=True)),
                ("auto_send", models.BooleanField(default=True)),
                (
                    "send_to_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "seller_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "seller_vat_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seller_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_country",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seller_country_iso",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "seller_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "seller_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "seller_bank_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_iban",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_swift",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("seller_is_person", models.BooleanField(blank=True, null=True)),
                ("seller_extra_info", models.TextField(blank=True, default="")),
                (
                    "buyer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "buyer_vat_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "buyer_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_country",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "buyer_country_iso",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "buyer_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "buyer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "buyer_bank_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_iban",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_swift",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("buyer_is_person", models.BooleanField(blank=True, null=True)),
                ("buyer_extra_info", models.TextField(blank=True, default="")),
                ("buyer_delivery_address", models.TextField(blank=True, default="")),
                ("issued_by", models.CharField(blank=True, default="", max_length=255)),
                (
                    "received_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("generation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices_as_buyer",
                        to="docscanner_app.counterparty",
                    ),
                ),
                (
                    "last_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_from_recurring_templates",
                        to="docscanner_app.invoice",
                    ),
                ),
                (
                    "seller_counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices_as_seller",
                        to="docscanner_app.counterparty",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurring_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_invoices",
                to="docscanner_app.recurringinvoice",
            ),
        ),
        migrations.CreateModel(
            name="RecurringInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Prekės pavadinimas",
                    ),
                ),
                (
                    "prekes_kodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės kodas",
                    ),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Prekės barkodas",
                    ),
                ),
                (
                    "preke_paslauga",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="Preke_paslauga",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="vnt",
                        max_length=50,
                        verbose_name="Mato vnt.",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Kaina",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="PVM %",
                    ),
                ),
                (
                    "discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "recurring_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="docscanner_app.recurringinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoiceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("error_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_runs",
                        to="docscanner_app.invoice",
                    ),
                ),
                (
                    "recurring_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="docscanner_app.recurringinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recurringinvoice",
            index=models.Index(
                fields=["user", "status"], name="idx_recinv_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoice",
            index=models.Index(
                fields=["status", "next_run_at"], name="idx_recinv_status_next"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoice",
            index=models.Index(
                fields=["user", "buyer_name"], name="idx_recinv_buyer_name"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoicelineitem",
            index=models.Index(
                fields=["recurring_invoice"], name="idx_recinvline_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvoicerun",
            index=models.Index(
                fields=["recurring_invoice", "status"],
                name="idx_recinvrun_parent_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoicerun",
            constraint=models.UniqueConstraint(
                fields=("recurring_invoice", "scheduled_for"),
                name="uniq_recinv_run_per_slot",
            ),
        ),
    ]
