# Generated by Django 6.0.3 on 2026-03-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0071_remove_invoice_atsakingo_asmens_kodas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="auto_create_sf_on_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="auto_sf_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="auto_sf_series",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="send_payment_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminder_days_after_due",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminder_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminder_interval_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="reminder_max_count",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="InvoiceEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Sąskaitos siuntimas"),
                            ("auto_sf", "Automatinė SF"),
                            ("reminder", "Priminimas"),
                            ("paid_notice", "Apmokėjimo patvirtinimas"),
                        ],
                        max_length=20,
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Išsiųsta"), ("failed", "Nepavyko")],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("error_text", models.TextField(blank=True, default="")),
                (
                    "reminder_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="docscanner_app.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "-sent_at"], name="idx_invemail_inv_sent"
                    ),
                    models.Index(
                        fields=["invoice", "email_type"], name="idx_invemail_inv_type"
                    ),
                ],
            },
        ),
    ]
