# Generated by Django 6.0.3 on 2026-03-13 09:19

import django.db.models.deletion
import docscanner_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0072_invoice_auto_create_sf_on_paid_invoice_auto_sf_send_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="last_payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Paskutinio mokėjimo data"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Apmokėta suma",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Juodraštis"),
                    ("issued", "Išrašyta"),
                    ("sent", "Išsiųsta"),
                    ("partially_paid", "Dalinai apmokėta"),
                    ("paid", "Apmokėta"),
                    ("cancelled", "Atšaukta"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("swedbank", "Swedbank"),
                            ("seb", "SEB"),
                            ("luminor", "Luminor"),
                            ("siauliu", "Šiaulių bankas"),
                            ("revolut", "Revolut"),
                            ("other", "Kitas"),
                        ],
                        max_length=50,
                        verbose_name="Bankas",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=docscanner_app.models.bank_statement_path,
                        verbose_name="Failas",
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xml", "XML (ISO 20022)")],
                        max_length=10,
                        verbose_name="Formatas",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "account_iban",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="IBAN"
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "period_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Laikotarpis nuo"
                    ),
                ),
                (
                    "period_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Laikotarpis iki"
                    ),
                ),
                (
                    "total_entries",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Iš viso įrašų"
                    ),
                ),
                (
                    "credit_entries",
                    models.PositiveIntegerField(default=0, verbose_name="Įplaukos"),
                ),
                (
                    "debit_entries",
                    models.PositiveIntegerField(default=0, verbose_name="Išlaidos"),
                ),
                (
                    "duplicates_skipped",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Praleisti dublikatai"
                    ),
                ),
                (
                    "auto_matched_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Automatiškai susieta"
                    ),
                ),
                (
                    "likely_matched_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Galimi atitikimai"
                    ),
                ),
                (
                    "unmatched_count",
                    models.PositiveIntegerField(default=0, verbose_name="Nesusieta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Įkeltas"),
                            ("processing", "Apdorojamas"),
                            ("processed", "Apdorotas"),
                            ("error", "Klaida"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bank_import", "Banko išrašas"),
                            ("payment_link", "Mokėjimo nuoroda"),
                            ("manual", "Rankinis"),
                            ("api", "API"),
                        ],
                        max_length=20,
                        verbose_name="Šaltinis",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Operacijos data")),
                (
                    "value_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valiutos data"
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Dok. nr."
                    ),
                ),
                (
                    "bank_operation_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="K=korespondentinis, MK=memorialinis, TT=tarptautinis, M=mokestis",
                        max_length=20,
                        verbose_name="Banko žyma",
                    ),
                ),
                (
                    "counterparty_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Mokėtojo/gavėjo pavadinimas",
                    ),
                ),
                (
                    "counterparty_name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "counterparty_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Įmonės/asmens kodas",
                    ),
                ),
                (
                    "counterparty_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Sąskaitos nr.",
                    ),
                ),
                (
                    "payment_purpose",
                    models.TextField(
                        blank=True, default="", verbose_name="Mokėjimo paskirtis"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nuorodos nr.",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Suma"
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Paslaugų teikėjas",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Mokėjimo ID",
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Nesusieta"),
                            ("auto_matched", "Automatiškai susieta"),
                            ("likely_matched", "Galimas atitikimas"),
                            ("confirmed", "Patvirtinta vartotojo"),
                            ("manually_matched", "Susieta rankiniu būdu"),
                            ("ignored", "Ignoruota"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                (
                    "match_confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("match_details", models.JSONField(blank=True, default=dict)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Paskirstyta suma",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transactions",
                        to="docscanner_app.bankstatement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OutgoingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bank_import", "Banko išrašas"),
                            ("payment_link", "Mokėjimo nuoroda"),
                            ("manual", "Rankinis"),
                            ("api", "API"),
                        ],
                        max_length=20,
                        verbose_name="Šaltinis",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Operacijos data")),
                (
                    "value_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valiutos data"
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Dok. nr."
                    ),
                ),
                (
                    "bank_operation_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="K=korespondentinis, MK=memorialinis, TT=tarptautinis, M=mokestis",
                        max_length=20,
                        verbose_name="Banko žyma",
                    ),
                ),
                (
                    "counterparty_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Mokėtojo/gavėjo pavadinimas",
                    ),
                ),
                (
                    "counterparty_name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "counterparty_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Įmonės/asmens kodas",
                    ),
                ),
                (
                    "counterparty_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Sąskaitos nr.",
                    ),
                ),
                (
                    "payment_purpose",
                    models.TextField(
                        blank=True, default="", verbose_name="Mokėjimo paskirtis"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nuorodos nr.",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Suma"
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Paslaugų teikėjas",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Mokėjimo ID",
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Nesusieta"),
                            ("auto_matched", "Automatiškai susieta"),
                            ("likely_matched", "Galimas atitikimas"),
                            ("confirmed", "Patvirtinta vartotojo"),
                            ("manually_matched", "Susieta rankiniu būdu"),
                            ("ignored", "Ignoruota"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                (
                    "match_confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("match_details", models.JSONField(blank=True, default=dict)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Paskirstyta suma",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transactions",
                        to="docscanner_app.bankstatement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bank_import", "Banko išrašas"),
                            ("payment_link", "Mokėjimo nuoroda"),
                            ("manual", "Rankinis"),
                            ("api", "API"),
                        ],
                        max_length=20,
                        verbose_name="Šaltinis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto", "Automatinis"),
                            ("proposed", "Pasiūlytas"),
                            ("confirmed", "Patvirtintas"),
                            ("manual", "Rankinis"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Paskirstyta suma"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mokėjimo data"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Patikimumas",
                    ),
                ),
                (
                    "match_reasons",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Atitikimo kriterijai"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="Pastaba"),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incoming_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="docscanner_app.incomingtransaction",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_allocations",
                        to="docscanner_app.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_bs_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingtransaction",
            index=models.Index(
                fields=["user", "-transaction_date"], name="idx_inc_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingtransaction",
            index=models.Index(
                fields=["user", "match_status"], name="idx_inc_user_match"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingtransaction",
            index=models.Index(fields=["transaction_hash"], name="idx_inc_hash"),
        ),
        migrations.AddIndex(
            model_name="incomingtransaction",
            index=models.Index(fields=["counterparty_code"], name="idx_inc_cpty_code"),
        ),
        migrations.AddIndex(
            model_name="outgoingtransaction",
            index=models.Index(
                fields=["user", "-transaction_date"], name="idx_out_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingtransaction",
            index=models.Index(fields=["transaction_hash"], name="idx_out_hash"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["invoice"], name="idx_pa_invoice"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["incoming_transaction"], name="idx_pa_txn"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["status"], name="idx_pa_status"),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("incoming_transaction__isnull", False)),
                fields=("incoming_transaction", "invoice"),
                name="uq_allocation_txn_inv",
            ),
        ),
    ]
