# Generated by Django 6.0.3 on 2026-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0073_invoice_last_payment_date_invoice_paid_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="payment_providers",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Mokėjimo nuorodų teikėjai"
            ),
        ),
    ]
