# Generated by Django 6.0.3 on 2026-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0074_customuser_payment_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_link_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_link_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="montonio / paysera / seb_paylink",
                max_length=30,
                verbose_name="Mokėjimo nuorodų teikėjas",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_link_provider_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UUID/ID from provider for webhook matching",
                max_length=255,
                verbose_name="Teikėjo mokėjimo ID",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_link_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Mokėjimo nuoroda"
            ),
        ),
    ]
