# Generated by Django 6.0.3 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0075_invoice_payment_link_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceemail",
            name="mailgun_message_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoiceemail",
            name="open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoiceemail",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceemail",
            name="reminder_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicesettings",
            name="invoice_reminder_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Dienos iki/po termino: neigiamos = prieš, teigiamos = po. Pvz: [-7, -1, 3]",
                verbose_name="Priminimų dienos",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Sąskaitos siuntimas"),
                    ("invoice_paid", "Apmokėta SF iš išankstinės"),
                    ("auto_sf", "Automatinė SF"),
                    ("reminder_before", "Priminimas prieš terminą"),
                    ("reminder_overdue", "Priminimas po termino"),
                    ("reminder", "Priminimas"),
                    ("manual_reminder", "Rankinis priminimas"),
                    ("cancelled", "Sąskaita atšaukta"),
                    ("paid_notice", "Apmokėjimo patvirtinimas"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Laukiama"),
                    ("sent", "Išsiųsta"),
                    ("failed", "Nepavyko"),
                    ("bounced", "Atmesta"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceemail",
            index=models.Index(
                fields=["mailgun_message_id"], name="idx_invemail_msgid"
            ),
        ),
    ]
