# Generated by Django 6.0.3 on 2026-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0076_invoiceemail_mailgun_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_last_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
