# Generated by Django 6.0.3 on 2026-03-19 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0077_invoice_email_last_status_invoice_email_sent_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Sąskaitos siuntimas"),
                    ("invoice_paid", "Apmokėta SF iš išankstinės"),
                    ("invoice_info", "Informacinė sąskaita"),
                    ("auto_sf", "Automatinė SF"),
                    ("reminder_before", "Priminimas prieš terminą"),
                    ("reminder_overdue", "Priminimas po termino"),
                    ("reminder", "Priminimas"),
                    ("manual_reminder", "Rankinis priminimas"),
                    ("cancelled", "Sąskaita atšaukta"),
                    ("paid_notice", "Apmokėjimo patvirtinimas"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CreditUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_used",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "document_filename",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("document_deleted_by_user", models.BooleanField(default=False)),
                ("document_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scanned_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_usage_logs",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
