# Generated by Django 6.0.3 on 2026-03-20 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0078_alter_invoiceemail_email_type_creditusagelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free (basic)"),
                            ("trial", "Trial"),
                            ("active", "Active (paid)"),
                        ],
                        default="free",
                        max_length=16,
                    ),
                ),
                ("trial_used", models.BooleanField(default=False)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("plan", models.CharField(blank=True, max_length=50, null=True)),
                ("plan_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inv_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inv subscription",
                "verbose_name_plural": "Inv subscriptions",
            },
        ),
        migrations.CreateModel(
            name="InvMonthlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="YYYY-MM format, e.g. 2026-03", max_length=7
                    ),
                ),
                ("exported_invoice_ids", models.JSONField(blank=True, default=list)),
                ("emailed_invoice_ids", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inv_monthly_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inv monthly usage",
                "verbose_name_plural": "Inv monthly usages",
                "unique_together": {("user", "month")},
            },
        ),
    ]
