# Generated by Django 6.0.3 on 2026-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0079_invsubscription_invmonthlyusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="invoice_pdf_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_type",
            field=models.CharField(db_index=True, default="credits", max_length=20),
        ),
        migrations.AddField(
            model_name="payments",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="plan",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_invoice_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
