# Generated by Django 6.0.3 on 2026-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0080_payments_invoice_pdf_url_payments_payment_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invsubscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="payments",
            name="stripe_invoice_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
