# Generated by Django 6.0.3 on 2026-03-25 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0081_invsubscription_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="rivile_api_kodas_po",
            field=models.CharField(
                blank=True,
                help_text="Grąžintas Rivile GAMA operacijos numeris",
                max_length=20,
                verbose_name="Rivile operacijos numeris (I06_KODAS_PO)",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="rivile_api_last_try",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rivile API paskutinis bandymas"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="rivile_api_status",
            field=models.CharField(
                blank=True,
                help_text="success / partial_success / error",
                max_length=20,
                null=True,
                verbose_name="Rivile API statusas",
            ),
        ),
        migrations.CreateModel(
            name="RivileGamaAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Pvz. 'UAB Mano Įmonė' — laisvos formos pavadinimas",
                        max_length=150,
                        verbose_name="Pavadinimas",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="Unikalus įmonės kodas, pvz. 123456789",
                        max_length=50,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        help_text="Fernet-encrypted API key",
                        verbose_name="API raktas (šifruotas)",
                    ),
                ),
                (
                    "key_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Paskutiniai 4 simboliai rodymui UI",
                        max_length=8,
                        verbose_name="Rakto pabaiga",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktyvus"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Patikrinimo laikas"
                    ),
                ),
                (
                    "last_ok",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Paskutinis patikrinimas OK"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Paskutinė klaida"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rivile_gama_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rivile GAMA API raktas",
                "verbose_name_plural": "Rivile GAMA API raktai",
                "ordering": ["created_at"],
                "unique_together": {("user", "company_code")},
            },
        ),
        migrations.CreateModel(
            name="RivileAPIRefLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Session ID пачки экспорта",
                        max_length=64,
                        verbose_name="Eksporto sesija",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="EDIT_N08_FULL / EDIT_N17 / EDIT_N25",
                        max_length=30,
                        verbose_name="API metodas",
                    ),
                ),
                (
                    "entity_code",
                    models.CharField(
                        help_text="N08_KODAS_KS / N17_KODAS_PS / N25_KODAS_BS",
                        max_length=50,
                        verbose_name="Objekto kodas",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Success", "Success"),
                            ("Error", "Error"),
                            ("Duplicate", "Duplicate"),
                        ],
                        max_length=20,
                        verbose_name="Statusas",
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(default=0, verbose_name="HTTP statusas"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Klaidos kodas"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Klaidos pranešimas"),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, verbose_name="Atsakymas (raw)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_logs",
                        to="docscanner_app.rivilegamaapikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rivile API ref log",
                "verbose_name_plural": "Rivile API ref logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "method", "entity_code"],
                        name="idx_rivile_ref_key_method_code",
                    ),
                    models.Index(
                        fields=["api_key", "method", "status"],
                        name="idx_rivile_ref_key_method_status",
                    ),
                ],
            },
        ),
    ]
