# Generated by Django 6.0.3 on 2026-03-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0082_scanneddocument_rivile_api_kodas_po_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rivileapireflog",
            new_name="idx_riv_ref_mth_code",
            old_name="idx_rivile_ref_key_method_code",
        ),
        migrations.RenameIndex(
            model_name="rivileapireflog",
            new_name="idx_riv_ref_mth_stat",
            old_name="idx_rivile_ref_key_method_status",
        ),
    ]
