# Generated by Django 6.0.3 on 2026-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0083_rename_idx_rivile_ref_key_method_code_idx_riv_ref_mth_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringinvoice",
            name="auto_create_sf_on_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recurringinvoice",
            name="auto_sf_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recurringinvoice",
            name="auto_sf_series",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="recurringinvoice",
            name="send_payment_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("rivile_gama_api", "Rivilė GAMA (per API)"),
                    ("stekas", "Stekas Plius"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
