# Generated by Django 6.0.3 on 2026-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0084_recurringinvoice_auto_create_sf_on_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="archive_file_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
