# Generated by Django 6.0.3 on 2026-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0085_scanneddocument_archive_file_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_link_url",
            field=models.URLField(
                blank=True, default="", max_length=1024, verbose_name="Mokėjimo nuoroda"
            ),
        ),
    ]
