# Generated by Django 6.0.3 on 2026-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0086_alter_invoice_payment_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="rivile_api_kodas_po",
            field=models.CharField(
                blank=True,
                help_text="Grąžintas Rivile GAMA operacijos numeris",
                max_length=20,
                verbose_name="Rivile operacijos numeris (I06_KODAS_PO)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="rivile_api_last_try",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rivile API paskutinis bandymas"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="rivile_api_status",
            field=models.CharField(
                blank=True,
                help_text="success / partial_success / error",
                max_length=20,
                null=True,
                verbose_name="Rivile API statusas",
            ),
        ),
        migrations.AlterField(
            model_name="apiexportlog",
            name="invoice_status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="apiexportlog",
            name="program",
            field=models.CharField(
                choices=[
                    ("optimum", "Optimum"),
                    ("dineta", "Dineta"),
                    ("rivile_gama_api", "Rivile GAMA API"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exportsession",
            name="program",
            field=models.CharField(
                choices=[
                    ("optimum", "Optimum"),
                    ("dineta", "Dineta"),
                    ("rivile_gama_api", "Rivile GAMA API"),
                ],
                max_length=50,
            ),
        ),
    ]
