# Generated by Django 6.0.3 on 2026-04-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0087_invoice_rivile_api_kodas_po_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="enhanced_ocr_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="enhanced_ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
