# Generated by Django 6.0.3 on 2026-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0088_scanneddocument_enhanced_ocr_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringinvoice",
            name="payment_link_provider",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
