# Generated by Django 6.0.3 on 2026-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0089_recurringinvoice_payment_link_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="adresas",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Adresas"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="aob_kodas",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
