# Generated by Django 6.0.3 on 2026-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0090_company_adresas_company_aob_kodas_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="company",
            name="docscanner__im_koda_e5674d_idx",
        ),
        migrations.AlterField(
            model_name="company",
            name="im_kodas",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
