# Generated by Django 6.0.3 on 2026-04-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0091_remove_company_docscanner__im_koda_e5674d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="normalized_pavadinimas",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["normalized_pavadinimas"], name="docscanner__normali_209969_idx"
            ),
        ),
    ]
