# Generated by Django 6.0.3 on 2026-04-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0092_company_normalized_pavadinimas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIProviderKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("rivile_gama_api", "Rivile GAMA API"),
                            ("dineta", "Dineta"),
                            ("optimum", "Optimum"),
                        ],
                        max_length=30,
                        verbose_name="Teikėjas",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Pavadinimas"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="Įmonės kodas, '__all__' visoms, '__israsymas__' išrašymui",
                        max_length=50,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "credentials_encrypted",
                    models.TextField(verbose_name="Prisijungimo duomenys (šifruoti)"),
                ),
                (
                    "key_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Paskutiniai 4 simboliai rodymui UI",
                        max_length=8,
                        verbose_name="Rakto pabaiga",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktyvus"),
                ),
                (
                    "use_for_all",
                    models.BooleanField(
                        default=False,
                        help_text="Jei True, šis raktas naudojamas kai nėra specifinio rakto įmonei",
                        verbose_name="Naudoti visoms įmonėms",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Patikrinimo laikas"
                    ),
                ),
                (
                    "last_ok",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Paskutinis patikrinimas OK"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Paskutinė klaida"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_provider_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API provider key",
                "verbose_name_plural": "API provider keys",
                "ordering": ["provider", "created_at"],
                "unique_together": {("user", "provider", "company_code")},
            },
        ),
    ]
