# Generated by Django 6.0.3 on 2026-04-09 10:04

from django.db import migrations


def migrate_forward(apps, schema_editor):
    """Переносит данные из RivileGamaAPIKey + dineta_settings + optimum_settings в APIProviderKey."""
    import json
    
    APIProviderKey = apps.get_model("docscanner_app", "APIProviderKey")
    RivileGamaAPIKey = apps.get_model("docscanner_app", "RivileGamaAPIKey")
    CustomUser = apps.get_model("docscanner_app", "CustomUser")

    # 1. Rivile GAMA API keys — копируем как есть
    #    credentials_encrypted уже Fernet-зашифрован, но формат другой:
    #    в RivileGamaAPIKey это зашифрованный raw string (api_key),
    #    а в APIProviderKey это зашифрованный JSON {"api_key": "..."}
    #    Поэтому пересоздаём через set_credentials нельзя (нет доступа к методам в миграции).
    #    Копируем encrypted as-is и пометим флагом для lazy-миграции.
    
    from docscanner_app.services.encryption import encrypt_value, decrypt_value

    for old in RivileGamaAPIKey.objects.all():
        # Расшифровываем старый ключ и зашифровываем в новом формате (JSON)
        try:
            raw_key = decrypt_value(old.api_key_encrypted)
            new_encrypted = encrypt_value(json.dumps({"api_key": raw_key}))
        except Exception:
            # Если расшифровка не удалась — пропускаем
            continue

        APIProviderKey.objects.create(
            user_id=old.user_id,
            provider="rivile_gama_api",
            label=old.label,
            company_code=old.company_code,
            credentials_encrypted=new_encrypted,
            key_suffix=old.key_suffix,
            is_active=old.is_active,
            use_for_all=False,
            verified_at=old.verified_at,
            last_ok=old.last_ok,
            last_error=old.last_error,
        )

    # 2. Dineta — из dineta_settings JSONField на CustomUser
    for user in CustomUser.objects.all():
        ds = user.dineta_settings
        if not ds or not isinstance(ds, dict):
            continue

        server = ds.get("server", "")
        client = ds.get("client", "")
        username = ds.get("username", "")
        password_enc = ds.get("password", "")

        if not any([server, username, password_enc]):
            continue

        # Собираем URL обратно из server+client
        url = f"{server.rstrip('/')}/{client}/" if server and client else server

        # password в dineta_settings зашифрован через password_encryption
        # Расшифровываем и кладём в новый формат
        from docscanner_app.utils.password_encryption import decrypt_password
        try:
            password = decrypt_password(password_enc) if password_enc else ""
        except Exception:
            password = ""

        creds = json.dumps({
            "url": url,
            "username": username,
            "password": password,
        })
        new_encrypted = encrypt_value(creds)

        APIProviderKey.objects.create(
            user_id=user.pk,
            provider="dineta",
            label="Dineta",
            company_code="__all__",
            credentials_encrypted=new_encrypted,
            key_suffix=username[-4:] if len(username) >= 4 else username,
            is_active=True,
            use_for_all=True,
        )

    # 3. Optimum — из optimum_settings JSONField на CustomUser
    for user in CustomUser.objects.all():
        os = user.optimum_settings
        if not os or not isinstance(os, dict):
            continue

        raw_key = os.get("key", "")
        if not raw_key:
            continue

        creds = json.dumps({"api_key": raw_key})
        new_encrypted = encrypt_value(creds)

        APIProviderKey.objects.create(
            user_id=user.pk,
            provider="optimum",
            label="Optimum",
            company_code="__all__",
            credentials_encrypted=new_encrypted,
            key_suffix=raw_key[-4:] if len(raw_key) >= 4 else raw_key,
            is_active=True,
            use_for_all=True,
            verified_at=os.get("verified_at"),
            last_ok=os.get("last_ok"),
            last_error=os.get("last_error", ""),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0093_apiproviderkey"),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrations.RunPython.noop),
    ]
