# Generated by Django 6.0.3 on 2026-04-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0094_migrate_api_keys_to_universal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rivileapireflog",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_logs",
                to="docscanner_app.apiproviderkey",
            ),
        ),
    ]