# Generated by Django 6.0.3 on 2026-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0095_update_reflog_fk_to_apiproviderkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportsession",
            name="invoice_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="inv_export_sessions",
                to="docscanner_app.invoice",
            ),
        ),
        migrations.RemoveIndex(
            model_name="apiexportlog",
            name="docscanner__documen_504cef_idx",
        ),
        migrations.AlterField(
            model_name="apiexportlog",
            name="document",
            field=models.IntegerField(
                verbose_name="Dokumento ID",
                db_index=True,
                help_text="ScannedDocument arba Invoice ID",
            ),
        ),
        migrations.AddIndex(
            model_name="apiexportlog",
            index=models.Index(
                fields=["document_id", "program", "-created_at"],
                name="idx_explog_doc_prog",
            ),
        ),
    ]
