# Generated by Django 6.0.3 on 2026-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0097_apiexportlog_document_to_int"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientautocomplete",
            name="is_person",
            field=models.BooleanField(default=False, verbose_name="Fizinis asmuo"),
        ),
    ]
