# Generated by Django 6.0.3 on 2026-04-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0098_clientautocomplete_is_person"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientautocomplete",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("imones_kodas__isnull", True), _negated=True),
                    models.Q(("imones_kodas", ""), _negated=True),
                ),
                fields=("user", "imones_kodas"),
                name="unique_client_code_per_user",
            ),
        ),
    ]
