# Generated by Django 6.0.3 on 2026-04-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0099_clientautocomplete_unique_client_code_per_user"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apiexportlog",
            name="idx_explog_doc_prog",
        ),
    ]
