# Generated by Django 6.0.3 on 2026-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0100_remove_apiexportlog_idx_explog_doc_prog"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apiexportlog",
            name="idx_explog_doc_prog",
        ),
        migrations.AddField(
            model_name="customuser",
            name="onboarding_email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Onboarding laiško išsiuntimo data"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="registration_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skaitmenizavimas", "Skaitmenizavimas"),
                    ("israsymas", "Sąskaitų išrašymas"),
                ],
                max_length=32,
                null=True,
                verbose_name="Registracijos šaltinis",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_expired_email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trial pabaigos laiško data"
            ),
        ),
    ]
