# Generated by Django 6.0.3 on 2026-04-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0101_remove_apiexportlog_idx_explog_doc_prog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="is_multi_doc_container",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="pre_extracted_ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="source_pages",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="multi_doc",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("rivile_gama_api", "Rivilė GAMA (per API)"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
