# Generated by Django 6.0.3 on 2026-05-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0102_scanneddocument_is_multi_doc_container_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientautocomplete",
            name="doc_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientautocomplete",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientautocomplete",
            name="name_normalized",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="clientautocomplete",
            name="source",
            field=models.CharField(
                choices=[("imported", "Importuotas"), ("document", "Iš dokumentų")],
                default="imported",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="clientautocomplete",
            index=models.Index(
                fields=["user", "pvm_kodas"], name="docscanner__user_id_527da9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientautocomplete",
            index=models.Index(
                fields=["user", "name_normalized"],
                name="docscanner__user_id_5c050c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clientautocomplete",
            index=models.Index(
                fields=["user", "source", "-doc_count"],
                name="docscanner__user_id_38434c_idx",
            ),
        ),
    ]
