# Generated by Django 6.0.3 on 2026-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0103_clientautocomplete_doc_count_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientautocomplete",
            name="unique_client_code_per_user",
        ),
        migrations.AddConstraint(
            model_name="clientautocomplete",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("imones_kodas__isnull", True), _negated=True),
                    models.Q(("imones_kodas", ""), _negated=True),
                ),
                fields=("user", "imones_kodas", "source"),
                name="unique_client_code_source_per_user",
            ),
        ),
    ]
