# Generated by Django 6.0.3 on 2026-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0104_remove_clientautocomplete_unique_client_code_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="is_credit_invoice",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True = kreditinė sąskaita faktūra (grąžinimas/nuolaida)",
                null=True,
                verbose_name="Kreditinė SF",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="is_debit_invoice",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True = debetinė sąskaita faktūra (papildomas mokestis)",
                null=True,
                verbose_name="Debetinė SF",
            ),
        ),
    ]
