# Generated by Django 6.0.3 on 2026-06-09 09:29

import django.db.models.deletion
import docscanner_app.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0105_scanneddocument_is_credit_invoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaybillUploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        db_index=True,
                        default="detaliai",
                        help_text="Važtaraščiai visada skenuojami 'detaliai'",
                        max_length=32,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("uploading", "uploading"),
                            ("credit_check", "credit_check"),
                            ("queued", "queued"),
                            ("processing", "processing"),
                            ("done", "done"),
                            ("blocked", "blocked"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="uploading",
                        max_length=32,
                    ),
                ),
                ("client_total_files", models.PositiveIntegerField(default=0)),
                ("uploaded_files", models.PositiveIntegerField(default=0)),
                ("uploaded_bytes", models.BigIntegerField(default=0)),
                ("expected_items", models.PositiveIntegerField(default=0)),
                ("actual_items", models.PositiveIntegerField(default=0)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("done_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("pending_archives", models.PositiveIntegerField(default=0)),
                ("archive_formats", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reserved_credits",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reserved_items", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("multi_doc", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waybill_upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaybillChunkedUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_size", models.BigIntegerField()),
                ("chunk_size", models.IntegerField()),
                ("total_chunks", models.IntegerField()),
                ("received", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "uploading"),
                            ("complete", "complete"),
                            ("failed", "failed"),
                        ],
                        default="uploading",
                        max_length=16,
                    ),
                ),
                ("tmp_path", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waybill_chunked_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunked_uploads",
                        to="docscanner_app.waybilluploadsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScannedWaybill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=docscanner_app.models.waybill_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Tikrinami"),
                            ("processing", "Vykdomi"),
                            ("completed", "Atlikti (Neeksportuoti)"),
                            ("rejected", "Atmesti"),
                            ("exported", "Atlikti (Eksportuoti)"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("preview_url", models.URLField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("glued_raw_text", models.TextField(blank=True, null=True)),
                ("gpt_raw_json", models.JSONField(blank=True, null=True)),
                ("structured_json", models.JSONField(blank=True, null=True)),
                ("enhanced_ocr_text", models.TextField(blank=True, null=True)),
                (
                    "enhanced_ocr_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "waybill_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oro", "Oro važtaraštis"),
                            ("prekiu", "Prekių važtaraštis"),
                            ("transporto", "Transporto važtaraštis"),
                            ("cmr", "CMR važtaraštis"),
                            ("kita", "Kita"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Važtaraščio tipas",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: LocalTransportDocumentNumber",
                        max_length=100,
                        null=True,
                        verbose_name="Važtaraščio numeris",
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True,
                        help_text="i.VAZ: LocalTransportDocumentDate",
                        null=True,
                        verbose_name="Važtaraščio data",
                    ),
                ),
                (
                    "place_of_issue",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: PlaceOfIssueTransportDocument (FullAddress)",
                        max_length=256,
                        null=True,
                        verbose_name="Išrašymo vieta",
                    ),
                ),
                (
                    "consignor_reg_number",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: Consignor.RegistrationNumber (įm. kodas arba 'ND')",
                        max_length=35,
                        null=True,
                        verbose_name="Siuntėjo kodas",
                    ),
                ),
                (
                    "consignor_name",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: Consignor.Name",
                        max_length=256,
                        null=True,
                        verbose_name="Siuntėjo pavadinimas",
                    ),
                ),
                (
                    "consignor_address",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Siuntėjo adresas",
                    ),
                ),
                (
                    "consignor_country_iso",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Siuntėjo šalis (ISO)",
                    ),
                ),
                (
                    "consignee_reg_number",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: Consignee.RegistrationNumber",
                        max_length=35,
                        null=True,
                        verbose_name="Gavėjo kodas",
                    ),
                ),
                (
                    "consignee_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Gavėjo pavadinimas",
                    ),
                ),
                (
                    "consignee_address",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Gavėjo adresas",
                    ),
                ),
                (
                    "consignee_country_iso",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Gavėjo šalis (ISO)",
                    ),
                ),
                (
                    "transporter_reg_number",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: Transporter.RegistrationNumber",
                        max_length=35,
                        null=True,
                        verbose_name="Vežėjo kodas",
                    ),
                ),
                (
                    "transporter_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Vežėjo pavadinimas",
                    ),
                ),
                (
                    "transporter_address",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Vežėjo adresas",
                    ),
                ),
                (
                    "transport_means_id",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: IdentityOfTransportUnits (valst. nr.) / oro: ВС рег. номер",
                        max_length=35,
                        null=True,
                        verbose_name="Transporto priemonės Nr.",
                    ),
                ),
                (
                    "transport_means_model",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: MarqueModelTransportUnits / oro: aircraft type",
                        max_length=70,
                        null=True,
                        verbose_name="Transporto priemonės modelis",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: Driver.Name / oro: Operatorius",
                        max_length=70,
                        null=True,
                        verbose_name="Vairuotojo vardas",
                    ),
                ),
                (
                    "driver_surname",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: Driver.Surname",
                        max_length=70,
                        null=True,
                        verbose_name="Vairuotojo pavardė",
                    ),
                ),
                (
                    "ship_from_address",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: ShipFrom.LoadAddress",
                        max_length=256,
                        null=True,
                        verbose_name="Pakrovimo adresas",
                    ),
                ),
                (
                    "ship_from_country_iso",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Pakrovimo šalis (ISO)",
                    ),
                ),
                (
                    "ship_from_warehouse",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: ShipFrom.WarehouseID",
                        max_length=24,
                        null=True,
                        verbose_name="Pakrovimo sandėlis",
                    ),
                ),
                (
                    "ship_to_address",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: ShipTo.UnloadAddress",
                        max_length=256,
                        null=True,
                        verbose_name="Iškrovimo adresas",
                    ),
                ),
                (
                    "ship_to_country_iso",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Iškrovimo šalis (ISO)",
                    ),
                ),
                (
                    "ship_to_warehouse",
                    models.CharField(
                        blank=True,
                        help_text="i.VAZ: ShipTo.WarehouseID",
                        max_length=24,
                        null=True,
                        verbose_name="Iškrovimo sandėlis",
                    ),
                ),
                (
                    "time_of_dispatch",
                    models.DateTimeField(
                        blank=True,
                        help_text="i.VAZ: TimeOfDispatch",
                        null=True,
                        verbose_name="Išgabenimo laikas",
                    ),
                ),
                (
                    "estimated_time_of_arrival",
                    models.DateTimeField(
                        blank=True,
                        help_text="i.VAZ: EstimatedTimeOfArrival",
                        null=True,
                        verbose_name="Numatomas pristatymo laikas",
                    ),
                ),
                (
                    "weight_gross",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="i.VAZ: Weight.GrossWeight",
                        max_digits=13,
                        null=True,
                        verbose_name="Bruto svoris (kg)",
                    ),
                ),
                (
                    "weight_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="i.VAZ: Weight.NetWeight",
                        max_digits=13,
                        null=True,
                        verbose_name="Neto svoris (kg)",
                    ),
                ),
                (
                    "cargo_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="i.VAZ: DeliveryData.Value",
                        max_digits=18,
                        null=True,
                        verbose_name="Krovinio vertė",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="ISO 4217: EUR, USD ir t.t.",
                        max_length=3,
                        null=True,
                        verbose_name="Valiuta",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="pavedimu / grynais / kortele ir t.t.",
                        max_length=70,
                        null=True,
                        verbose_name="Mokėjimo būdas",
                    ),
                ),
                (
                    "payment_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="i.VAZ: PaymentForDelivery.PaymentValue",
                        max_digits=18,
                        null=True,
                        verbose_name="Mokėjimo suma",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="PVM %",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Iš viso / Total",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Pastabos"),
                ),
                (
                    "complementary_info",
                    models.TextField(
                        blank=True,
                        help_text="i.VAZ: ComplementaryDeliveryInformation",
                        null=True,
                        verbose_name="Papildoma informacija",
                    ),
                ),
                (
                    "airport_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Oro uostas"
                    ),
                ),
                (
                    "airport_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Oro uosto kodas (ICAO/IATA)",
                    ),
                ),
                (
                    "customer_iata_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Pirkėjo IATA kodas",
                    ),
                ),
                (
                    "aircraft_type",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Orlaivio tipas",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Skrydžio numeris",
                    ),
                ),
                (
                    "aircraft_registration",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Orlaivio registracijos numeris",
                    ),
                ),
                (
                    "flight_nature",
                    models.CharField(
                        blank=True,
                        help_text="komercinis / privatus / kita",
                        max_length=20,
                        null=True,
                        verbose_name="Skrydžio pobūdis",
                    ),
                ),
                (
                    "flight_type",
                    models.CharField(
                        blank=True,
                        help_text="1 = už ES ribų, ir t.t.",
                        max_length=10,
                        null=True,
                        verbose_name="Skrydžio tipas",
                    ),
                ),
                (
                    "meter_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Skaitiklis prieš užpildymą",
                    ),
                ),
                (
                    "meter_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Skaitiklis po užpildymo",
                    ),
                ),
                (
                    "meter_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Skaitiklio skirtumas",
                    ),
                ),
                (
                    "fuel_density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="Tankis (kg/l)",
                    ),
                ),
                (
                    "fuel_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatūra (°C)",
                    ),
                ),
                (
                    "quantity_liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=13,
                        null=True,
                        verbose_name="Kiekis (litrai)",
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=13,
                        null=True,
                        verbose_name="Kiekis (kg)",
                    ),
                ),
                (
                    "refueller_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Autocisternos numeris",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="pvz. JET A-1",
                        max_length=100,
                        null=True,
                        verbose_name="Produktas",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        help_text="pvz. 2710.19.21.0 / i.VAZ: ProductCode",
                        max_length=70,
                        null=True,
                        verbose_name="Produkto kodas (KN)",
                    ),
                ),
                (
                    "excise_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Akcizo tarifas",
                    ),
                ),
                (
                    "oro_document_subtype",
                    models.CharField(
                        blank=True,
                        help_text="delivery (užpilti) / defuelling (išpilti)",
                        max_length=20,
                        null=True,
                        verbose_name="Oro važtaraščio potipis",
                    ),
                ),
                ("counted_in_session", models.BooleanField(default=False)),
                ("uploaded_size_bytes", models.BigIntegerField(default=0)),
                ("is_archive_container", models.BooleanField(default=False)),
                ("archive_file_count", models.PositiveIntegerField(default=0)),
                (
                    "upload_batch_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_multi_doc_container", models.BooleanField(default=False)),
                ("source_pages", models.JSONField(blank=True, null=True)),
                ("pre_extracted_ocr_text", models.TextField(blank=True, null=True)),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="docscanner_app.scannedwaybill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waybills",
                        to="docscanner_app.waybilluploadsession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="waybilluploadsession",
            index=models.Index(
                fields=["user", "stage"], name="docscanner__user_id_626d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waybilluploadsession",
            index=models.Index(
                fields=["created_at"], name="docscanner__created_f499ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waybillchunkedupload",
            index=models.Index(
                fields=["user", "status"], name="docscanner__user_id_124d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waybillchunkedupload",
            index=models.Index(
                fields=["session", "status"], name="docscanner__session_348d12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="idx_wb_user_uploaded_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(
                fields=["user", "status", "-uploaded_at"],
                name="idx_wb_user_status_uploaded",
            ),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(
                fields=["user", "consignor_name"], name="idx_wb_user_consignor"
            ),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(
                fields=["user", "consignee_name"], name="idx_wb_user_consignee"
            ),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(
                fields=["upload_session"], name="docscanner__upload__0f7cb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(
                fields=["parent_document"], name="docscanner__parent__b93d70_idx"
            ),
        ),
    ]
