# Generated by Django 6.0.3 on 2026-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0106_waybilluploadsession_waybillchunkedupload_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scannedwaybill",
            name="idx_wb_user_consignor",
        ),
        migrations.RemoveIndex(
            model_name="scannedwaybill",
            name="idx_wb_user_consignee",
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="airport",
            field=models.CharField(
                blank=True,
                help_text="pvz. KUN / Kaunas",
                max_length=100,
                null=True,
                verbose_name="Oro uostas",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="buyer_address",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Pirkėjo adresas"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="buyer_iata_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="IATA kodas"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="buyer_name",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Pirkėjo pavadinimas",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="buyer_remark_half_income",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Half income from transportation",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="buyer_remark_other",
            field=models.TextField(
                blank=True, null=True, verbose_name="Kitos pastabos"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="buyer_vat_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="PVM kodas"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="company_representative",
            field=models.CharField(
                blank=True,
                max_length=140,
                null=True,
                verbose_name="Operatorius / atstovas",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="defuelling_receipt",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Defuelling receipt (kurai išpilti)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="delivery_receipt",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Delivery receipt (kurai užpilti)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="density_observed",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=6,
                null=True,
                verbose_name="Tankis (faktinis)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="density_standard",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=6,
                null=True,
                verbose_name="Tankis (+15°C)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="from_airport_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Iš (oro uosto kodas)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="from_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Iš (miestas)"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="from_country_iso",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Iš (šalis ISO)"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="outside_eu",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Už ES ribų"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invoice", "Invoice"),
                    ("fuelling_card", "Fuelling card"),
                    ("cash", "Cash"),
                    ("credit_card", "Credit card"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Mokėjimo būdas",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="quantity_kg_observed",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=13,
                null=True,
                verbose_name="Kilogramai (faktinis)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="quantity_liters_observed",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=13,
                null=True,
                verbose_name="Litrai (faktinis)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="quantity_liters_standard",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=13,
                null=True,
                verbose_name="Litrai (+15°C)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="reading_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Po užpildymo",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="reading_before",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Prieš užpildymą",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="reading_difference",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Skirtumas",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="temperature_observed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Temperatūra °C (faktinė)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="temperature_standard",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Temperatūra °C (+15°C)",
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="time_arrival",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Arrival"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="time_departure",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Departure"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="time_finish",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Finish"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="time_return",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Return"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="time_start",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Start"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="to_airport_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Į (oro uosto kodas)"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="to_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Į (miestas)"
            ),
        ),
        migrations.AddField(
            model_name="scannedwaybill",
            name="to_country_iso",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Į (šalis ISO)"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="document_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Važtaraščio data"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="document_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Važtaraščio numeris",
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="flight_nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commercial", "Commercial"),
                    ("private", "Private"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Skrydžio pobūdis",
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="flight_type",
            field=models.CharField(
                blank=True,
                help_text="pvz. 1",
                max_length=10,
                null=True,
                verbose_name="Tipas",
            ),
        ),
        migrations.AlterField(
            model_name="waybilluploadsession",
            name="scan_type",
            field=models.CharField(db_index=True, default="detaliai", max_length=32),
        ),
        migrations.AddIndex(
            model_name="scannedwaybill",
            index=models.Index(fields=["user", "buyer_name"], name="idx_wb_user_buyer"),
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="aircraft_registration",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="airport_code",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="airport_name",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="cargo_value",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="complementary_info",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignee_address",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignee_country_iso",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignee_name",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignee_reg_number",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignor_address",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignor_country_iso",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignor_name",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="consignor_reg_number",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="customer_iata_code",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="driver_surname",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="estimated_time_of_arrival",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="excise_rate",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="flight_number",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="fuel_density",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="fuel_temperature",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="meter_after",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="meter_before",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="meter_difference",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="note",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="oro_document_subtype",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="payment_value",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="place_of_issue",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="product_code",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="quantity_kg",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="quantity_liters",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="ship_from_address",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="ship_from_country_iso",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="ship_from_warehouse",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="ship_to_address",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="ship_to_country_iso",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="ship_to_warehouse",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="time_of_dispatch",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="transport_means_id",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="transport_means_model",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="transporter_address",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="transporter_name",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="transporter_reg_number",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="vat_percent",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="waybill_type",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="weight_gross",
        ),
        migrations.RemoveField(
            model_name="scannedwaybill",
            name="weight_net",
        ),
    ]
