# Generated by Django 6.0.3 on 2026-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0107_remove_scannedwaybill_idx_wb_user_consignor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_waybill_access",
            field=models.BooleanField(
                default=False,
                help_text="Ar vartotojas mato važtaraščių modulį meniu",
                verbose_name="Važtaraščių prieiga",
            ),
        ),
    ]
