# Generated by Django 6.0.3 on 2026-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0108_customuser_has_waybill_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scannedwaybill",
            name="aircraft_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Orlaivio tipas"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="flight_nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commercial", "Commercial"),
                    ("private", "Private"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Skrydžio pobūdis",
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="flight_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tipas"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invoice", "Invoice"),
                    ("fuelling_card", "Fuelling card"),
                    ("cash", "Cash"),
                    ("credit_card", "Credit card"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Mokėjimo būdas",
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="refueller_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Autocisternos numeris",
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="time_arrival",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Arrival"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="time_departure",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Departure"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="time_finish",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Finish"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="time_return",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Return"
            ),
        ),
        migrations.AlterField(
            model_name="scannedwaybill",
            name="time_start",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Start"
            ),
        ),
    ]
