# Generated by Django 6.0.3 on 2026-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0109_alter_scannedwaybill_aircraft_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_replace_rules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="buyer_replaced_by_rule",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="seller_replaced_by_rule",
            field=models.BooleanField(default=False),
        ),
    ]
