# Generated by Django 6.0.3 on 2026-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0110_customuser_company_replace_rules_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="traded_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("services", "Paslaugos"),
                    ("goods", "Prekės"),
                    ("mixed", "Mišrus"),
                ],
                max_length=12,
                null=True,
                verbose_name="Prekė/Paslauga/Mišrus",
            ),
        ),
    ]
