# Generated by Django 6.0.3 on 2026-06-23 13:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0111_scanneddocument_traded_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="min_ilgalaikis_turtas_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("500.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="is_long_term_asset_candidate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="suggested_asset_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
