# Generated by Django 6.0.3 on 2026-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0112_customuser_min_ilgalaikis_turtas_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="is_long_term_asset_candidate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="suggested_asset_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
