# Generated by Django 6.0.3 on 2026-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0113_lineitem_is_long_term_asset_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="min_ilgalaikis_turtas_amount",
            field=models.IntegerField(default=500),
        ),
    ]
