# Generated by Django 6.0.3 on 2026-07-01 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0115_newslettercampaign_newsletterrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("imone", "Įmonė (UAB, MB, IĮ, ...)"),
                            ("iv", "Individuali veikla"),
                        ],
                        max_length=10,
                        verbose_name="Veiklos tipas",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Pavadinimas")),
                (
                    "vat_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="PVM kodas"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresas"
                    ),
                ),
                (
                    "country_iso",
                    models.CharField(default="LT", max_length=10, verbose_name="Šalis"),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Savininko vardas, pavardė",
                    ),
                ),
                (
                    "iv_certificate_nr",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="IV pažymėjimo nr.",
                    ),
                ),
                (
                    "accounting_program",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rivile", "Rivilė GAMA"),
                            ("rivile_erp", "Rivilė ERP"),
                            ("bss", "BSS"),
                            ("finvalda", "Finvalda"),
                            ("apskaita5", "Apskaita5"),
                            ("centas", "Centas"),
                            ("agnum", "Agnum"),
                            ("pragma3", "Pragma 3.2"),
                            ("pragma4", "Pragma 4"),
                            ("butent", "Būtent"),
                            ("dineta", "Dineta"),
                            ("optimum", "Optimum"),
                            ("debetas", "Debetas"),
                            ("site_pro", "Site.Pro (B1)"),
                            ("apsa", "APSA"),
                            ("isaf", "iSAF"),
                            ("paulita", "Paulita"),
                            ("rivile_gama_api", "Rivilė GAMA (per API)"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Apskaitos programa",
                    ),
                ),
                (
                    "payment_providers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Mokėjimo nuorodų teikėjai",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Įmonės profilis",
                "verbose_name_plural": "Įmonių profiliai",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="active_company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="docscanner_app.companyprofile",
                verbose_name="Aktyvi įmonė",
            ),
        ),
    ]
