# Generated by Django 6.0.3 on 2026-07-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0116_customuser_onboarding_completed_companyprofile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_documents",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="debeto_saskaita",
            field=models.CharField(
                blank=True,
                help_text="Pvz. 2410 (pirkėjų skolos)",
                max_length=20,
                null=True,
                verbose_name="Debeto sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="kredito_saskaita",
            field=models.CharField(
                blank=True,
                help_text="Pvz. 5001 (pardavimo pajamos)",
                max_length=20,
                null=True,
                verbose_name="Kredito sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="period",
            field=models.DateField(
                blank=True, null=True, verbose_name="Apskaitos periodas"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pvm_saskaita",
            field=models.CharField(
                blank=True,
                help_text="Pvz. 449 (pardavimo PVM)",
                max_length=20,
                null=True,
                verbose_name="PVM sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="scanned_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Jei sukurta iš skaitmenizavimo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices_from_scan",
                to="docscanner_app.scanneddocument",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="debeto_saskaita",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Debeto sąskaita"
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="kredito_saskaita",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Kredito sąskaita"
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="pvm_saskaita_kor",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="PVM sąskaita"
            ),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Naujas"), ("accounted", "Užpajamuotas")],
                        default="new",
                        max_length=16,
                        verbose_name="Dokumento statusas",
                    ),
                ),
                (
                    "exported",
                    models.BooleanField(default=False, verbose_name="Eksportuota"),
                ),
                (
                    "exported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eksportavimo data"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Neapmokėta"),
                            ("partially_paid", "Dalinai apmokėta"),
                            ("paid", "Apmokėta"),
                        ],
                        default="unpaid",
                        max_length=16,
                        verbose_name="Mokėjimo statusas",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Apmokėta suma",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Paskutinio mokėjimo data"
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        blank=True,
                        help_text="Mėnesio pirma diena, pvz. 2026-01-01",
                        null=True,
                        verbose_name="Apskaitos periodas",
                    ),
                ),
                (
                    "debeto_saskaita",
                    models.CharField(
                        blank=True,
                        help_text="Pvz. 2014 (prekės), 6001 (sąnaudos)",
                        max_length=20,
                        null=True,
                        verbose_name="Debeto sąskaita",
                    ),
                ),
                (
                    "kredito_saskaita",
                    models.CharField(
                        blank=True,
                        help_text="Pvz. 443 (tiekėjų skolos)",
                        max_length=20,
                        null=True,
                        verbose_name="Kredito sąskaita",
                    ),
                ),
                (
                    "pvm_saskaita",
                    models.CharField(
                        blank=True,
                        help_text="Pvz. 2492 (pirkimo PVM)",
                        max_length=20,
                        null=True,
                        verbose_name="PVM sąskaita",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_credit_invoice",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "is_debit_invoice",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "document_series",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("operation_date", models.DateField(blank=True, null=True)),
                (
                    "seller_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "seller_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "seller_vat_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "seller_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "seller_country_iso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "seller_iban",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seller_is_person", models.BooleanField(blank=True, null=True)),
                (
                    "seller_id_programoje",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buyer_name_normalized",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buyer_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Įmonės kodas",
                    ),
                ),
                (
                    "buyer_vat_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "buyer_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "buyer_country_iso",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("buyer_iban", models.CharField(blank=True, max_length=255, null=True)),
                ("buyer_is_person", models.BooleanField(blank=True, null=True)),
                (
                    "buyer_id_programoje",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "amount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "amount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "invoice_discount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "invoice_discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("separate_vat", models.BooleanField(blank=True, null=True)),
                ("doc_96_str", models.BooleanField(blank=True, null=True)),
                (
                    "pirkimas_pardavimas",
                    models.CharField(default="pirkimas", max_length=20),
                ),
                ("report_to_isaf", models.BooleanField(blank=True, null=True)),
                (
                    "document_type_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "prekes_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prekes_tipas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "preke_paslauga",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "objekto_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pvm_kodas", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "pvm_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tipo_kodas", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "tipo_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "projekto_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "serijos_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "centro_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "optimum_api_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("optimum_last_try_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dineta_api_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("dineta_last_try_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rivile_api_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("rivile_api_last_try", models.DateTimeField(blank=True, null=True)),
                (
                    "rivile_api_kodas_po",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "scanned_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Negalima ištrinti skaitmenizuoto dok. kol jis priskirtas pirkimams",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases_from_scan",
                        to="docscanner_app.scanneddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pirkimo dokumentas",
                "verbose_name_plural": "Pirkimo dokumentai",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prekes_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prekes_barkodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "prekes_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prekes_tipas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "preke_paslauga",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_with_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_wo_vat",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("is_long_term_asset_candidate", models.BooleanField(default=False)),
                (
                    "suggested_asset_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "sandelio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "sandelio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "objekto_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "objekto_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "padalinio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "padalinio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mokescio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "mokescio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "atsakingo_asmens_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "atsakingo_asmens_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "operacijos_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "operacijos_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "islaidu_straipsnio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "islaidu_straipsnio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pvm_kodas", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "pvm_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tipo_kodas", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "tipo_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "zurnalo_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "zurnalo_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "projekto_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "projekto_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "projekto_vadovo_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "projekto_vadovo_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "skyrio_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "skyrio_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "partijos_nr_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "partijos_nr_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "korespondencijos_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "korespondencijos_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "serijos_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "serijos_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "centro_kodas",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "centro_pavadinimas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "debeto_saskaita",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Debeto sąskaita",
                    ),
                ),
                (
                    "kredito_saskaita",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Kredito sąskaita",
                    ),
                ),
                (
                    "pvm_saskaita",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="PVM sąskaita",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="docscanner_app.purchase",
                    ),
                ),
                (
                    "source_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_lines",
                        to="docscanner_app.lineitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pirkimo eilutė",
                "verbose_name_plural": "Pirkimo eilutės",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["company_profile", "-created_at"], name="idx_purchase_profile"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_purchase_user"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["scanned_document"], name="idx_purchase_scan"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "seller_name_normalized"],
                name="idx_purchase_seller_norm",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("scanned_document", "company_profile"),
                name="unique_purchase_scan_per_company",
            ),
        ),
    ]
