# Generated by Django 6.0.3 on 2026-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0117_invoice_company_profile_invoice_debeto_saskaita_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="debeto_saskaita",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="kredito_saskaita",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="pvm_saskaita_kor",
        ),
        migrations.AddField(
            model_name="invoice",
            name="pirkimo_saskaita",
            field=models.CharField(
                blank=True,
                help_text="AI pasiūlytas pirkimo debeto sąskaitos kodas",
                max_length=20,
                null=True,
                verbose_name="Pirkimo sąskaita (AI)",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="pirkimo_saskaita",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Pirkimo sąskaita (AI)",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="pirkimo_saskaita",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Pirkimo sąskaita (AI)",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="pirkimo_saskaita",
            field=models.CharField(
                blank=True,
                help_text="AI pasiūlytas pirkimo debeto sąskaitos kodas",
                max_length=20,
                null=True,
                verbose_name="Pirkimo sąskaita (AI)",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("rivile_gama_api", "Rivilė GAMA (per API)"),
                    ("dokskenas_erp", "DokSkenas ERP"),
                ],
                max_length=32,
                null=True,
                verbose_name="Apskaitos programa",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("rivile_gama_api", "Rivilė GAMA (per API)"),
                    ("dokskenas_erp", "DokSkenas ERP"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
