# Generated by Django 6.0.3 on 2026-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0118_remove_invoicelineitem_debeto_saskaita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="pardavimo_saskaita",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Pardavimo sąskaita (user)",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="pardavimo_saskaita",
            field=models.CharField(
                blank=True,
                help_text="Vartotojo nustatyta pardavimo kredito sąskaita",
                max_length=20,
                null=True,
                verbose_name="Pardavimo sąskaita (user)",
            ),
        ),
    ]
