# Generated by Django 6.0.3 on 2026-07-07 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0119_lineitem_pardavimo_saskaita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="perkelta_i_apskaita",
            field=models.BooleanField(
                default=False, verbose_name="Perkelta į apskaitą"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="perkelta_i_apskaita_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Perkelta į apskaitą (data)"
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="perkelta_i_company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perkelti_dokumentai",
                to="docscanner_app.companyprofile",
                verbose_name="Perkelta į įmonę",
            ),
        ),
    ]
