# Generated by Django 6.0.3 on 2026-07-07 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0120_scanneddocument_perkelta_i_apskaita_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Pirkimas"),
                            ("sale", "Pardavimas"),
                            ("bank", "Bankas"),
                            ("manual", "Rankinis"),
                            ("opening", "Pradiniai likučiai"),
                        ],
                        max_length=12,
                        verbose_name="Šaltinio tipas",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        help_text="Operacijos data (pvz. SF data arba mokėjimo data)",
                        verbose_name="Įrašo data",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Mėnesio pirma diena, pvz. 2026-01-01",
                        verbose_name="Periodas",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dokumento nr.",
                    ),
                ),
                (
                    "counterparty_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Kontrahentas",
                    ),
                ),
                (
                    "counterparty_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Kontrahento kodas",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Aprašymas"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Juodraštis"),
                            ("posted", "Užregistruotas"),
                            ("needs_review", "Reikia peržiūros"),
                            ("unbalanced", "Nesubalansuotas"),
                            ("void", "Anuliuotas"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Statusas",
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="Debeto suma",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="Kredito suma",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="Skirtumas (D − K)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=10, verbose_name="Valiuta"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="docscanner_app.invoice",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="docscanner_app.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DK įrašas",
                "verbose_name_plural": "DK įrašai",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("D", "Debetas"), ("K", "Kreditas")],
                        max_length=1,
                        verbose_name="Pusė",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(max_length=20, verbose_name="Sąskaitos kodas"),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sąskaitos pavadinimas",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Suma"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Aprašymas"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="docscanner_app.journalentry",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_lines",
                        to="docscanner_app.invoicelineitem",
                    ),
                ),
                (
                    "purchase_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_lines",
                        to="docscanner_app.purchaseline",
                    ),
                ),
            ],
            options={
                "verbose_name": "DK įrašo eilutė",
                "verbose_name_plural": "DK įrašo eilutės",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company_profile", "-entry_date"], name="idx_je_profile_date"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company_profile", "period"], name="idx_je_profile_period"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company_profile", "source_type", "-entry_date"],
                name="idx_je_profile_source",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["purchase"], name="idx_je_purchase"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["invoice"], name="idx_je_invoice"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company_profile", "counterparty_code"],
                name="idx_je_counterparty",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(fields=["entry", "side"], name="idx_jel_entry_side"),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(fields=["account_code"], name="idx_jel_account"),
        ),
    ]
