# Generated by Django 6.0.3 on 2026-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0121_journalentry_journalentryline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="math_validation_passed",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="ready_for_export",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="seller_vat_val",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
