# Generated by Django 6.0.3 on 2026-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0123_remove_purchase_atsakingo_asmens_kodas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="kor_balanced",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
