# Generated by Django 6.0.3 on 2026-07-11 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0124_purchase_kor_balanced"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransactionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pvz. 'Caffeine kavos pirkimai', 'SEB mėnesio mokestis'",
                        max_length=255,
                        verbose_name="Pavadinimas",
                    ),
                ),
                (
                    "match_field",
                    models.CharField(
                        choices=[
                            ("counterparty_name", "Mokėtojo/gavėjo pavadinimas"),
                            ("counterparty_code", "Įmonės kodas"),
                            ("tx_type", "Transakcijos tipas"),
                            ("purpose_contains", "Mokėjimo paskirtis (ieško teksto)"),
                        ],
                        max_length=30,
                        verbose_name="Palyginimo laukas",
                    ),
                ),
                (
                    "match_operator",
                    models.CharField(
                        choices=[
                            ("contains", "Turi tekstą"),
                            ("exact", "Tiksliai sutampa"),
                            ("starts_with", "Prasideda"),
                            ("regex", "Regex"),
                        ],
                        default="contains",
                        max_length=20,
                        verbose_name="Palyginimo tipas",
                    ),
                ),
                (
                    "match_value",
                    models.CharField(
                        help_text="Pvz. 'CAFFEINE', 'SEB bankas', 'ACMTMDOPFEES'",
                        max_length=500,
                        verbose_name="Palyginimo reikšmė",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Visos"),
                            ("debit", "Tik išlaidos"),
                            ("credit", "Tik įplaukos"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Kryptis",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("", "Nekategorizuota"),
                            ("supplier_payment", "Mokėjimas tiekėjui"),
                            ("customer_receipt", "Įplauka iš pirkėjo"),
                            ("bank_fee", "Banko mokestis"),
                            ("pos_purchase", "Atsiskaitymas kortele"),
                            ("tax_vmi", "Mokestis VMI"),
                            ("tax_sodra", "Mokestis Sodrai"),
                            ("salary", "Darbo užmokestis"),
                            ("owner_personal", "Savininko lėšos"),
                            ("provider_payout", "Tarpininko išmoka"),
                            ("currency_exchange", "Valiutos keitimas"),
                            ("loan", "Paskola"),
                            ("refund", "Grąžinimas"),
                            ("other", "Kita"),
                        ],
                        max_length=30,
                        verbose_name="Kategorija",
                    ),
                ),
                (
                    "debit_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pvz. 6880, 6803, 4481",
                        max_length=20,
                        verbose_name="Debeto sąskaita",
                    ),
                ),
                (
                    "credit_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Jei tuščia – naudojama banko sąskaita",
                        max_length=20,
                        verbose_name="Kredito sąskaita",
                    ),
                ),
                (
                    "description_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pvz. 'Kava – {counterparty_name}'. Galimi kintamieji: {counterparty_name}, {amount}, {date}, {purpose}",
                        max_length=500,
                        verbose_name="Aprašymo šablonas",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Didesnis = svarbiau. Kai kelios taisyklės tinka – laimi didesnė.",
                        verbose_name="Prioritetas",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktyvi")),
                (
                    "auto_create_je",
                    models.BooleanField(
                        default=True,
                        help_text="Jei True – DK įrašas kuriamas automatiškai be patvirtinimo",
                        verbose_name="Automatiškai kurti DK įrašą",
                    ),
                ),
                (
                    "times_applied",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Panaudota kartų"
                    ),
                ),
                (
                    "last_applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paskutinį kartą"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banko operacijos taisyklė",
                "verbose_name_plural": "Banko operacijų taisyklės",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="paymentallocation",
            name="uq_allocation_txn_inv",
        ),
        migrations.RenameIndex(
            model_name="paymentallocation",
            new_name="idx_pa_inc_txn",
            old_name="idx_pa_txn",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="bank_accounts_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='IBAN → buhalterinė sąskaita. Formatas: {"LT19...": {"account": "2711", "bank": "seb", "label": "SEB pagrindinė"}}',
                verbose_name="Banko sąskaitų susiejimas",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="category_account_credit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jei tuščia, naudojama banko sąskaita iš IBAN mapping",
                max_length=20,
                verbose_name="Kredito sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="category_account_debit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sąskaitų plano sąskaita, pvz. 6880 (banko mokesčiai)",
                max_length=20,
                verbose_name="Debeto sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Sukurtas DK įrašas",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="docscanner_app.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("pos_purchase", "Atsiskaitymas kortele"),
                    ("tax_vmi", "Mokestis VMI"),
                    ("tax_sodra", "Mokestis Sodrai"),
                    ("salary", "Darbo užmokestis"),
                    ("owner_personal", "Savininko lėšos"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("currency_exchange", "Valiutos keitimas"),
                    ("loan", "Paskola"),
                    ("refund", "Grąžinimas"),
                    ("other", "Kita"),
                ],
                default="",
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="category_account_credit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jei tuščia, naudojama banko sąskaita iš IBAN mapping",
                max_length=20,
                verbose_name="Kredito sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="category_account_debit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sąskaitų plano sąskaita, pvz. 6880 (banko mokesčiai)",
                max_length=20,
                verbose_name="Debeto sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Sukurtas DK įrašas",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="docscanner_app.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("pos_purchase", "Atsiskaitymas kortele"),
                    ("tax_vmi", "Mokestis VMI"),
                    ("tax_sodra", "Mokestis Sodrai"),
                    ("salary", "Darbo užmokestis"),
                    ("owner_personal", "Savininko lėšos"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("currency_exchange", "Valiutos keitimas"),
                    ("loan", "Paskola"),
                    ("refund", "Grąžinimas"),
                    ("other", "Kita"),
                ],
                default="",
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="DK įrašas sukurtas patvirtinus susiejimą",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_allocations",
                to="docscanner_app.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="outgoing_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="docscanner_app.outgoingtransaction",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="docscanner_app.purchase",
            ),
        ),
        migrations.AlterField(
            model_name="incomingtransaction",
            name="bank_operation_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Swedbank: K/MK/TT/M. SEB: TRANSAKCIJOS TIPAS. Luminor: operacijos tipas.",
                max_length=255,
                verbose_name="Banko žyma / transakcijos tipas",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingtransaction",
            name="bank_operation_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Swedbank: K/MK/TT/M. SEB: TRANSAKCIJOS TIPAS. Luminor: operacijos tipas.",
                max_length=255,
                verbose_name="Banko žyma / transakcijos tipas",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_allocations",
                to="docscanner_app.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="source",
            field=models.CharField(
                choices=[
                    ("bank_import", "Banko išrašas"),
                    ("payment_link", "Mokėjimo nuoroda"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("manual", "Rankinis"),
                    ("api", "API"),
                ],
                max_length=20,
                verbose_name="Šaltinis",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["purchase"], name="idx_pa_purchase"),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["outgoing_transaction"], name="idx_pa_out_txn"),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("incoming_transaction__isnull", False), ("invoice__isnull", False)
                ),
                fields=("incoming_transaction", "invoice"),
                name="uq_allocation_inc_inv",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("outgoing_transaction__isnull", False), ("purchase__isnull", False)
                ),
                fields=("outgoing_transaction", "purchase"),
                name="uq_allocation_out_purch",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invoice__isnull", True), ("purchase__isnull", True), _negated=True
                ),
                name="chk_allocation_has_document",
            ),
        ),
        migrations.AddField(
            model_name="banktransactionrule",
            name="company_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transaction_rules",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="banktransactionrule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transaction_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="category_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Taisyklė, kuri priskyrė kategoriją automatiškai",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="docscanner_app.banktransactionrule",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="category_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Taisyklė, kuri priskyrė kategoriją automatiškai",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="docscanner_app.banktransactionrule",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransactionrule",
            index=models.Index(
                fields=["user", "company_profile", "is_active"],
                name="idx_btr_user_cp_active",
            ),
        ),
    ]
