# Generated by Django 6.0.3 on 2026-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0125_banktransactionrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="kor_balanced",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Korespondencija subalansuota",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="math_validation_passed",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Sumos sutampa"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ready_for_export",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Paruošta registravimui",
            ),
        ),
    ]
