# Generated by Django 6.0.3 on 2026-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0126_invoice_kor_balanced_invoice_math_validation_passed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="kredito_saskaita",
            field=models.CharField(
                blank=True,
                help_text="Pvz. 5000 / 5001",
                max_length=20,
                null=True,
                verbose_name="Pardavimo pajamų sąskaita",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="pvm_saskaita",
            field=models.CharField(
                blank=True,
                help_text="Pvz. 4492",
                max_length=20,
                null=True,
                verbose_name="PVM sąskaita",
            ),
        ),
    ]
