# Generated by Django 6.0.3 on 2026-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0127_invoicelineitem_kredito_saskaita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingtransaction",
            name="matched_document_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Užpildoma automatiškai per matching",
                max_length=100,
                verbose_name="Susieto dokumento numeris",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="matched_document_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Užpildoma automatiškai per matching",
                max_length=100,
                verbose_name="Susieto dokumento numeris",
            ),
        ),
        migrations.AlterField(
            model_name="banktransactionrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("tax_vmi", "VMI mokestis"),
                    ("tax_sodra", "Sodra / VSDFV"),
                    ("salary", "Darbo užmokestis"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("owner_withdrawal", "Savininko lėšų paėmimas"),
                    ("owner_deposit", "Savininko įnašas"),
                    ("loan_payment", "Paskolos grąžinimas"),
                    ("loan_received", "Gauta paskola"),
                    ("refund_received", "Gautas grąžinimas"),
                    ("other_expense", "Kitos sąnaudos"),
                    ("other_income", "Kitos pajamos"),
                ],
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="incomingtransaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("tax_vmi", "VMI mokestis"),
                    ("tax_sodra", "Sodra / VSDFV"),
                    ("salary", "Darbo užmokestis"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("owner_withdrawal", "Savininko lėšų paėmimas"),
                    ("owner_deposit", "Savininko įnašas"),
                    ("loan_payment", "Paskolos grąžinimas"),
                    ("loan_received", "Gauta paskola"),
                    ("refund_received", "Gautas grąžinimas"),
                    ("other_expense", "Kitos sąnaudos"),
                    ("other_income", "Kitos pajamos"),
                ],
                default="",
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingtransaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("tax_vmi", "VMI mokestis"),
                    ("tax_sodra", "Sodra / VSDFV"),
                    ("salary", "Darbo užmokestis"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("owner_withdrawal", "Savininko lėšų paėmimas"),
                    ("owner_deposit", "Savininko įnašas"),
                    ("loan_payment", "Paskolos grąžinimas"),
                    ("loan_received", "Gauta paskola"),
                    ("refund_received", "Gautas grąžinimas"),
                    ("other_expense", "Kitos sąnaudos"),
                    ("other_income", "Kitos pajamos"),
                ],
                default="",
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
    ]
