# Generated by Django 6.0.3 on 2026-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0128_incomingtransaction_matched_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="duplicate_details",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Dublikatų detalės"
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="own_account_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="own_account_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
    ]
