# Generated by Django 6.0.3 on 2026-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0129_bankstatement_duplicate_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingtransaction",
            name="reference_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nuorodos nr."
            ),
        ),
        migrations.AlterField(
            model_name="outgoingtransaction",
            name="reference_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nuorodos nr."
            ),
        ),
    ]
