# Generated by Django 6.0.3 on 2026-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0130_alter_incomingtransaction_reference_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingtransaction",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("unmatched", "Nesusieta"),
                    ("auto_matched", "Automatiškai susieta"),
                    ("likely_matched", "Galimas atitikimas"),
                    ("confirmed", "Patvirtinta vartotojo"),
                    ("manually_matched", "Susieta rankiniu būdu"),
                    ("ignored", "Ignoruota"),
                    ("classified", "Kategorizuota"),
                ],
                default="unmatched",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="outgoingtransaction",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("unmatched", "Nesusieta"),
                    ("auto_matched", "Automatiškai susieta"),
                    ("likely_matched", "Galimas atitikimas"),
                    ("confirmed", "Patvirtinta vartotojo"),
                    ("manually_matched", "Susieta rankiniu būdu"),
                    ("ignored", "Ignoruota"),
                    ("classified", "Kategorizuota"),
                ],
                default="unmatched",
                max_length=20,
            ),
        ),
    ]
