# Generated by Django 6.0.3 on 2026-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0131_alter_incomingtransaction_match_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productautocomplete",
            name="unit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Mato vienetas"
            ),
        ),
    ]
