# Generated by Django 6.0.3 on 2026-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0132_productautocomplete_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="matched_preke_paslauga",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                verbose_name="Susietos prekės / paslaugos tipas",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="matched_prekes_barkodas",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Susietos prekės barkodas",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="matched_prekes_kodas",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Susietos prekės kodas",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="matched_prekes_pavadinimas",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Susietos prekės pavadinimas",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="matched_unit",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Susietos prekės mato vienetas",
            ),
        ),
    ]
