# Generated by Django 6.0.3 on 2026-07-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0133_lineitem_matched_preke_paslauga_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="matched_catalog_json",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Katalogo susiejimo atsakymas (JSON)",
            ),
        ),
    ]
