# Generated by Django 6.0.3 on 2026-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0134_scanneddocument_matched_catalog_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="catalog_match_user_override",
            field=models.BooleanField(
                default=False,
                verbose_name="Vartotojas pakeitė/atšaukė katalogo susiejimą",
            ),
        ),
    ]
