# Generated by Django 6.0.3 on 2026-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0135_lineitem_catalog_match_user_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="catalog_unmatched_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
