# Generated by Django 6.0.3 on 2026-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0136_scanneddocument_catalog_unmatched_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingtransaction",
            name="amount_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Konvertuota suma EUR. Jei currency=EUR, lygi amount.",
                max_digits=12,
                null=True,
                verbose_name="Suma eurais",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="exchange_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Banko konvertavimo komisinis, EUR",
                max_digits=12,
                verbose_name="Valiutos keitimo mokestis",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="1 EUR = X valiutos vienetų, pvz. 1.1000 (USD)",
                max_digits=12,
                null=True,
                verbose_name="Valiutos kursas",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="exchange_rate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Valiutos kurso data"
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=12,
                null=True,
                verbose_name="Valiutos kursas",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="exchange_rate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Valiutos kurso data"
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="original_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Originali suma",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="original_currency",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Originali valiuta"
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="amount_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Konvertuota suma EUR. Jei currency=EUR, lygi amount.",
                max_digits=12,
                null=True,
                verbose_name="Suma eurais",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="exchange_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Banko konvertavimo komisinis, EUR",
                max_digits=12,
                verbose_name="Valiutos keitimo mokestis",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="1 EUR = X valiutos vienetų, pvz. 1.1000 (USD)",
                max_digits=12,
                null=True,
                verbose_name="Valiutos kursas",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="exchange_rate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Valiutos kurso data"
            ),
        ),
    ]
