# Generated by Django 6.0.3 on 2026-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0137_incomingtransaction_amount_eur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentryline",
            name="is_user_modified",
            field=models.BooleanField(default=False),
        ),
    ]
