# Generated by Django 6.0.3 on 2026-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0138_journalentryline_is_user_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="counterparty_vat_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Kontrahento PVM kodas",
            ),
        ),
    ]
