# Generated by Django 6.0.3 on 2026-07-31 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0139_journalentry_counterparty_vat_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringinvoice",
            name="company_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_invoices_cp",
                to="docscanner_app.companyprofile",
            ),
        ),
    ]
