# Generated by Django 6.0.3 on 2026-07-31 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0140_recurringinvoice_company_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterparty",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counterparties",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="measurementunit",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurement_units",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="docscanner_app.companyprofile",
            ),
        ),
    ]
