# Generated by Django 6.0.3 on 2026-07-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0141_counterparty_company_profile_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="counterparty",
            name="unique_user_company_code",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_user_product_kodas",
        ),
        migrations.AlterUniqueTogether(
            name="measurementunit",
            unique_together={("user", "company_profile", "code")},
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_code", ""), _negated=True),
                fields=("user", "company_profile", "company_code"),
                name="unique_user_company_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("user", "company_profile", "kodas"),
                name="unique_user_product_kodas",
            ),
        ),
    ]
