# Generated by Django 6.0.3 on 2026-08-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0142_remove_counterparty_unique_user_company_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceseries",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_series",
                to="docscanner_app.companyprofile",
            ),
        ),
    ]
