# Generated by Django 6.0.3 on 2026-08-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0143_invoiceseries_company_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoiceseries",
            unique_together={("user", "company_profile", "prefix")},
        ),
    ]
