# Generated by Django 6.0.3 on 2026-08-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0144_alter_invoiceseries_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Banko pavadinimas"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="El. paštas"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefonas"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="swift",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="SWIFT/BIC"
            ),
        ),
    ]
