# Generated by Django 6.0.3 on 2026-08-04 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0145_companyprofile_bank_name_companyprofile_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesettings",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_settings",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="invoicesettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
