# Generated by Django 6.0.3 on 2026-08-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0146_invoicesettings_company_profile_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoicesettings",
            unique_together={("user", "company_profile")},
        ),
    ]
