# Generated by Django 6.0.3 on 2026-08-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0147_alter_invoicesettings_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_address",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_bank_name",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_company_code",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_email",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_iban",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_name",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_phone",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_swift",
        ),
        migrations.RemoveField(
            model_name="invoicesettings",
            name="seller_vat_code",
        ),
    ]
