# Generated by Django 6.0.3 on 2026-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0148_remove_invoicesettings_seller_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_credit_invoice",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
