# Generated by Django 6.0.3 on 2026-08-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0149_invoice_is_credit_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_statements",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transactions",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transactions",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["company_profile", "-created_at"], name="idx_bs_cp_created"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingtransaction",
            index=models.Index(
                fields=["company_profile", "match_status"], name="idx_inc_cp_match"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingtransaction",
            index=models.Index(
                fields=["company_profile", "-transaction_date"], name="idx_out_cp_date"
            ),
        ),
    ]
