# Generated by Django 6.0.3 on 2026-08-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0150_bankstatement_company_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("swedbank", "Swedbank"),
                    ("seb", "SEB"),
                    ("luminor", "Luminor"),
                    ("siauliu", "Artea"),
                    ("revolut", "Revolut"),
                    ("other", "Kitas"),
                ],
                max_length=50,
                verbose_name="Bankas",
            ),
        ),
    ]
