# Generated by Django 6.0.3 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0151_alter_bankstatement_bank_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="uses_inventory",
            field=models.BooleanField(
                default=False,
                help_text="Jei įjungta, prekės perpardavimui keliamos į 2040 (atsargos). Jei išjungta, jos keliamos tiesiai į sąnaudas (6002).",
                verbose_name="Naudoja sandėlio apskaitą",
            ),
        ),
    ]
