# Generated by Django 6.0.3 on 2026-08-08 05:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0152_companyprofile_uses_inventory"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinklarastisIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("search_text", models.TextField(blank=True, default="")),
                (
                    "cat_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("youtube", 3),
                            ("code", 4),
                            ("quote", 5),
                            ("table", 10),
                            ("divider", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "full title"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "h5",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "image",
                                        "blockquote",
                                    ]
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Вставь YouTube ссылку"},
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Вставь кодовый блок"},
                            ),
                            5: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            7: ("wagtail.blocks.CharBlock", (), {}),
                            8: ("wagtail.blocks.ListBlock", (7,), {}),
                            9: ("wagtail.blocks.StreamBlock", [[("row", 8)]], {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 6), ("data", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {"label": "Space line"},
                            ),
                        },
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("search_text", models.TextField(blank=True, default="")),
                (
                    "main_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
