# Generated by Django 5.1.3 on 2026-08-11 12:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0153_tinklarastisindexpage_blogcategorypage_blogpostpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("youtube", 3),
                    ("download_button", 6),
                    ("code", 7),
                    ("quote", 8),
                    ("table", 13),
                    ("divider", 14),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "image",
                                "blockquote",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Вставь YouTube ссылку"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Atsisiųsti",
                            "label": "Mygtuko tekstas",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Pvz.: /media/sablonai/saskaita.xlsx",
                            "label": "Failo kelias arba URL",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 4), ("file_url", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Вставь кодовый блок"},
                    ),
                    8: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    10: ("wagtail.blocks.CharBlock", (), {}),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: ("wagtail.blocks.StreamBlock", [[("row", 11)]], {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("caption", 9), ("data", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"label": "Space line"},
                    ),
                },
            ),
        ),
    ]
