# Generated by Django 5.1.3 on 2026-08-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0154_alter_blogpostpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="transit_accounts_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='channel:provider → buhalterinė sąskaita (273 grupė). Formatas: {"payment_link:montonio": {"account": "2731", "channel": "payment_link", "provider": "montonio", "label": "Montonio", "currency": "EUR"}}',
                verbose_name="Tarpinių (agregatorių) sąskaitų susiejimas",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="manual_aggregator_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jei užpildyta — ši incoming operacija laikoma agregatoriaus išmoka (payout).",
                max_length=32,
                verbose_name="Rankiniu būdu pažymėtas agregatorius",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="source",
            field=models.CharField(
                choices=[
                    ("bank_import", "Banko išrašas"),
                    ("payment_link", "Mokėjimo nuoroda"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("ecommerce", "E-parduotuvė"),
                    ("manual", "Rankinis"),
                    ("api", "API"),
                ],
                max_length=20,
                verbose_name="Šaltinis",
            ),
        ),
    ]
