# Generated by Django 5.1.3 on 2026-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0155_companyprofile_transit_accounts_mapping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("swedbank", "Swedbank"),
                    ("seb", "SEB"),
                    ("luminor", "Luminor"),
                    ("siauliu", "Artea"),
                    ("revolut", "Revolut"),
                    ("paypal", "PayPal"),
                    ("other", "Kitas"),
                ],
                max_length=50,
                verbose_name="Bankas",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="file_format",
            field=models.CharField(
                choices=[("csv", "CSV"), ("xml", "XML (ISO 20022)"), ("xlsx", "XLSX")],
                max_length=10,
                verbose_name="Formatas",
            ),
        ),
    ]
