# Generated by Django 5.1.3 on 2026-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0156_alter_bankstatement_bank_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingtransaction",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="PayPal/banko komisinis operacijos valiuta. Visada teigiamas.",
                max_digits=12,
                verbose_name="Komisinis mokestis",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransaction",
            name="fee_amount_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Komisinis EUR. Jei currency=EUR — lygus fee_amount.",
                max_digits=12,
                null=True,
                verbose_name="Komisinis mokestis EUR",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="PayPal/banko komisinis operacijos valiuta. Visada teigiamas.",
                max_digits=12,
                verbose_name="Komisinis mokestis",
            ),
        ),
        migrations.AddField(
            model_name="outgoingtransaction",
            name="fee_amount_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Komisinis EUR. Jei currency=EUR — lygus fee_amount.",
                max_digits=12,
                null=True,
                verbose_name="Komisinis mokestis EUR",
            ),
        ),
    ]
