# Generated by Django 5.1.3 on 2026-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0158_alter_banktransactionrule_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="site_pro_api_extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="apiproviderkey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("rivile_gama_api", "Rivile GAMA API"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("site_pro_api", "Site.pro"),
                ],
                max_length=30,
                verbose_name="Teikėjas",
            ),
        ),
    ]
