# Generated by Django 5.1.3 on 2026-08-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0159_customuser_site_pro_api_extra_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="site_pro_api_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="site_pro_last_try_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="site_pro_api_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="site_pro_last_try_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("site_pro_api", "Site.pro (per API)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("rivile_gama_api", "Rivilė GAMA (per API)"),
                    ("dokskenas_erp", "DokSkenas ERP"),
                ],
                max_length=32,
                null=True,
                verbose_name="Apskaitos programa",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_accounting_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rivile", "Rivilė GAMA"),
                    ("rivile_erp", "Rivilė ERP"),
                    ("bss", "BSS"),
                    ("finvalda", "Finvalda"),
                    ("apskaita5", "Apskaita5"),
                    ("centas", "Centas"),
                    ("agnum", "Agnum"),
                    ("pragma3", "Pragma 3.2"),
                    ("pragma4", "Pragma 4"),
                    ("butent", "Būtent"),
                    ("dineta", "Dineta"),
                    ("optimum", "Optimum"),
                    ("debetas", "Debetas"),
                    ("site_pro", "Site.Pro (B1)"),
                    ("site_pro_api", "Site.pro (per API)"),
                    ("apsa", "APSA"),
                    ("isaf", "iSAF"),
                    ("paulita", "Paulita"),
                    ("rivile_gama_api", "Rivilė GAMA (per API)"),
                    ("dokskenas_erp", "DokSkenas ERP"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
