# Generated by Django 5.1.3 on 2026-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0160_invoice_site_pro_api_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiexportarticlelog",
            name="kind",
            field=models.CharField(blank=True, default="item", max_length=10),
        ),
    ]
