# Generated by Django 5.1.3 on 2026-08-28 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0162_alter_banktransactionrule_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDKTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Pavadinimas")),
                ("direction", models.CharField(default="both", max_length=10)),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Kategorija"
                    ),
                ),
                ("lines", models.JSONField(default=list)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dk_templates",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dk_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-times_used", "name"],
                "indexes": [
                    models.Index(
                        fields=["company_profile", "-times_used"],
                        name="idx_dktpl_profile_used",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_profile", "name"), name="uq_dk_template_name"
                    )
                ],
            },
        ),
    ]
