# Generated by Django 5.1.3 on 2026-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0163_userdktemplate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdktemplate",
            options={
                "ordering": ["-times_used", "name"],
                "verbose_name": "DK šablonas",
                "verbose_name_plural": "DK šablonai",
            },
        ),
        migrations.AlterField(
            model_name="userdktemplate",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Neprivaloma: susieja šabloną su transaction_category",
                max_length=40,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="userdktemplate",
            name="direction",
            field=models.CharField(
                choices=[
                    ("outgoing", "Išlaidos"),
                    ("incoming", "Įplaukos"),
                    ("both", "Abi"),
                ],
                default="both",
                max_length=10,
                verbose_name="Kryptis",
            ),
        ),
        migrations.AlterField(
            model_name="userdktemplate",
            name="lines",
            field=models.JSONField(
                default=list, verbose_name="Korespondencijos eilutės"
            ),
        ),
    ]
