# Generated by Django 5.1.3 on 2026-08-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0165_incomingtransaction_deferred_until_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentallocation",
            name="chk_allocation_has_document",
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_allocations",
                to="docscanner_app.counterparty",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="counterparty_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="counterparty_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("document", "Dokumentas"),
                    ("advance", "Avansas"),
                    ("writeoff", "Nurašymas"),
                ],
                default="document",
                max_length=12,
                verbose_name="Tipas",
            ),
        ),
        migrations.AlterField(
            model_name="banktransactionrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("tax_vmi", "VMI mokestis"),
                    ("tax_sodra", "Sodra / VSDFV"),
                    ("salary", "Darbo užmokestis"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("tax_customs", "Muitinės mokestis"),
                    ("owner_withdrawal", "Savininko lėšų paėmimas"),
                    ("owner_deposit", "Savininko įnašas"),
                    ("loan_payment", "Paskolos grąžinimas"),
                    ("loan_received", "Gauta paskola"),
                    ("refund_received", "Gautas grąžinimas"),
                    ("payment_refund", "Mokėjimo grąžinimas"),
                    ("payment_reversal", "Mokėjimo atšaukimas"),
                    ("chargeback", "Chargeback"),
                    ("paypal_card_funding", "PayPal sąskaitos papildymas"),
                    ("internal_transfer", "Vidinis pervedimas"),
                    ("other_expense", "Kitos sąnaudos"),
                    ("manual_dk", "Apdorota rankiniu būdu"),
                    ("other_income", "Kitos pajamos"),
                    ("shopify_pardavimas", "Shopify pardavimas"),
                ],
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="incomingtransaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("tax_vmi", "VMI mokestis"),
                    ("tax_sodra", "Sodra / VSDFV"),
                    ("salary", "Darbo užmokestis"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("tax_customs", "Muitinės mokestis"),
                    ("owner_withdrawal", "Savininko lėšų paėmimas"),
                    ("owner_deposit", "Savininko įnašas"),
                    ("loan_payment", "Paskolos grąžinimas"),
                    ("loan_received", "Gauta paskola"),
                    ("refund_received", "Gautas grąžinimas"),
                    ("payment_refund", "Mokėjimo grąžinimas"),
                    ("payment_reversal", "Mokėjimo atšaukimas"),
                    ("chargeback", "Chargeback"),
                    ("paypal_card_funding", "PayPal sąskaitos papildymas"),
                    ("internal_transfer", "Vidinis pervedimas"),
                    ("other_expense", "Kitos sąnaudos"),
                    ("manual_dk", "Apdorota rankiniu būdu"),
                    ("other_income", "Kitos pajamos"),
                    ("shopify_pardavimas", "Shopify pardavimas"),
                ],
                default="",
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingtransaction",
            name="transaction_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nekategorizuota"),
                    ("supplier_payment", "Mokėjimas tiekėjui"),
                    ("customer_receipt", "Įplauka iš pirkėjo"),
                    ("bank_fee", "Banko mokestis"),
                    ("tax_vmi", "VMI mokestis"),
                    ("tax_sodra", "Sodra / VSDFV"),
                    ("salary", "Darbo užmokestis"),
                    ("provider_payout", "Tarpininko išmoka"),
                    ("tax_customs", "Muitinės mokestis"),
                    ("owner_withdrawal", "Savininko lėšų paėmimas"),
                    ("owner_deposit", "Savininko įnašas"),
                    ("loan_payment", "Paskolos grąžinimas"),
                    ("loan_received", "Gauta paskola"),
                    ("refund_received", "Gautas grąžinimas"),
                    ("payment_refund", "Mokėjimo grąžinimas"),
                    ("payment_reversal", "Mokėjimo atšaukimas"),
                    ("chargeback", "Chargeback"),
                    ("paypal_card_funding", "PayPal sąskaitos papildymas"),
                    ("internal_transfer", "Vidinis pervedimas"),
                    ("other_expense", "Kitos sąnaudos"),
                    ("manual_dk", "Apdorota rankiniu būdu"),
                    ("other_income", "Kitos pajamos"),
                    ("shopify_pardavimas", "Shopify pardavimas"),
                ],
                default="",
                max_length=30,
                verbose_name="Kategorija",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["kind"], name="idx_pa_kind"),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "document"), _negated=True),
                    models.Q(
                        ("invoice__isnull", True),
                        ("purchase__isnull", True),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="chk_allocation_has_document",
            ),
        ),
    ]
