# Generated by Django 5.1.3 on 2026-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0166_allocation_kind_counterparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentallocation",
            name="amount_txn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kiek nurašoma nuo operacijos likučio. Kai valiutos sutampa = amount",
                max_digits=12,
                null=True,
                verbose_name="Paskirstyta suma operacijos valiuta",
            ),
        ),
    ]
