# Generated by Django 5.1.3 on 2026-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0167_allocation_amount_txn"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentallocation",
            name="amount_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kiek realiai judėjo banko sąskaitoje, EUR",
                max_digits=12,
                null=True,
                verbose_name="Paskirstyta suma EUR (banko pusė)",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="doc_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="1 EUR = X dokumento valiutos, dokumento datai. Skolos pusė skaičiuojama juo.",
                max_digits=12,
                null=True,
                verbose_name="Dokumento valiutos kursas",
            ),
        ),
    ]
