# Generated by Django 5.1.3 on 2026-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0168_paymentallocation_amount_eur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adclick",
            name="page_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="adclick",
            name="referrer",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="needs_account",
            field=models.BooleanField(
                default=False,
                help_text="Rankinis mokėjimas be nurodytos sąskaitos — DK įrašas dar nesukurtas.",
                verbose_name="Trūksta pinigų sąskaitos",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Iš kur sumokėta: 271x bankas, kasa ar kt. Tik rankiniams mokėjimams.",
                max_length=20,
                verbose_name="Pinigų sąskaita",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(fields=["needs_account"], name="idx_pa_needs_acc"),
        ),
    ]
