# Generated by Django 5.1.3 on 2026-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0169_adclick_page_url_adclick_referrer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="epris_codes",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='[{"code": "1", "subcode": "1.1.2", "free_text": "", "language": ""}, ...]',
                null=True,
                verbose_name="EPRIS prekių kodai",
            ),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="epris_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="scanneddocument",
            name="epris_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
