# Generated by Django 5.1.3 on 2026-09-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0171_scanneddocument_epris_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterpartyBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="counterparty",
            name="unique_user_company_code",
        ),
        migrations.RemoveIndex(
            model_name="counterparty",
            name="idx_cp_user_name_norm",
        ),
        migrations.RemoveIndex(
            model_name="counterparty",
            name="idx_cp_user_code",
        ),
        migrations.AddField(
            model_name="counterparty",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Rankinis"),
                    ("israsymas", "Išrašymas"),
                    ("transfer", "Perkėlimas į apskaitą"),
                    ("opening", "Pradiniai likučiai"),
                    ("bank", "Banko išrašas"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="company_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counterparties",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="name_normalized",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(
                fields=["company_profile", "name_normalized"],
                name="idx_cp_prof_name_norm",
            ),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(
                fields=["company_profile", "company_code"], name="idx_cp_prof_code"
            ),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(
                fields=["company_profile", "vat_code"], name="idx_cp_prof_vat"
            ),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_code", ""), _negated=True),
                fields=("company_profile", "company_code"),
                name="unique_cp_profile_company_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vat_code", ""), _negated=True),
                fields=("company_profile", "vat_code"),
                name="unique_cp_profile_vat_code",
            ),
        ),
        migrations.AddField(
            model_name="counterpartybankaccount",
            name="company_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counterparty_bank_accounts",
                to="docscanner_app.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="counterpartybankaccount",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="docscanner_app.counterparty",
            ),
        ),
        migrations.AddConstraint(
            model_name="counterpartybankaccount",
            constraint=models.UniqueConstraint(
                fields=("company_profile", "iban"),
                name="unique_cp_bank_account_profile_iban",
            ),
        ),
    ]
