# Generated by Django 5.1.3 on 2026-09-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0172_counterpartybankaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentryline",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_lines",
                to="docscanner_app.counterparty",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="seller_counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases_as_seller",
                to="docscanner_app.counterparty",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["counterparty", "account_code"], name="idx_jel_cp_account"
            ),
        ),
    ]
