# Generated by Django 5.1.3 on 2026-09-13 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0173_journalentryline_counterparty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningBalanceBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cutover_date",
                    models.DateField(
                        help_text="Pirma diena, nuo kurios dirbama DokSkenas ERP",
                        verbose_name="Perėjimo data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Juodraštis"), ("confirmed", "Patvirtinta")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "diff_policy",
                    models.CharField(
                        choices=[
                            ("ask", "Klausti"),
                            ("unassigned", "Priskirti be kontrahento"),
                        ],
                        default="ask",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balance_batch",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opening_batch",
                        to="docscanner_app.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pradinių likučių partija",
                "verbose_name_plural": "Pradinių likučių partijos",
            },
        ),
        migrations.CreateModel(
            name="AccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_code", models.CharField(max_length=40)),
                (
                    "external_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("account_code", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_mappings",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_profile", "external_code"),
                        name="uq_account_mapping_per_profile",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("balance", "Balansas"),
                            ("bank", "Banko sąskaitos"),
                            ("counterparty", "Kontrahentai"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "amount_currency",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "mapped_account",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "mapped_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Tikslus kodas"),
                            ("prefix", "Pagal kodo pradžią"),
                            ("name", "Pagal pavadinimą"),
                            ("saved", "Iš ankstesnio susiejimo"),
                            ("manual", "Pasirinkta rankiniu būdu"),
                            ("none", "Nesusieta"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "counterparty_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "counterparty_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "counterparty_vat_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("row_number", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="docscanner_app.openingbalancebatch",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="docscanner_app.counterparty",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "row_number", "id"],
                "indexes": [
                    models.Index(
                        fields=["batch", "section"], name="idx_obline_batch_section"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("balance", "Balansas"),
                            ("bank", "Banko sąskaitos"),
                            ("counterparty", "Kontrahentai"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="docscanner_app.openingbalancebatch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "section"), name="uq_opening_section_per_batch"
                    )
                ],
            },
        ),
    ]
