# Generated by Django 5.1.3 on 2026-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0174_openingbalancebatch_accountmapping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingbalanceline",
            name="section",
            field=models.CharField(
                choices=[
                    ("balance", "Balansas"),
                    ("bank", "Banko sąskaitos"),
                    ("buyer", "Pirkėjų skolos"),
                    ("supplier", "Tiekėjų skolos"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancesection",
            name="section",
            field=models.CharField(
                choices=[
                    ("balance", "Balansas"),
                    ("bank", "Banko sąskaitos"),
                    ("buyer", "Pirkėjų skolos"),
                    ("supplier", "Tiekėjų skolos"),
                ],
                max_length=20,
            ),
        ),
    ]
