# Generated by Django 5.1.3 on 2026-09-15 11:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0175_alter_openingbalanceline_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Pirkimas"),
                    ("sale", "Pardavimas"),
                    ("bank", "Bankas"),
                    ("manual", "Rankinis"),
                    ("opening", "Pradiniai likučiai"),
                    ("fixed_asset", "Ilgalaikis turtas"),
                ],
                max_length=12,
                verbose_name="Šaltinio tipas",
            ),
        ),
        migrations.CreateModel(
            name="FixedAssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kompiuterinė technika", "Kompiuterinė technika"),
                            ("ryšių priemonės", "Ryšių priemonės"),
                            ("programinė įranga", "Programinė įranga"),
                            ("įsigytos teisės", "Įsigytos teisės"),
                            ("baldai", "Baldai"),
                            ("lengvasis automobilis", "Lengvasis automobilis"),
                            ("krovininis automobilis", "Krovininis automobilis"),
                            ("mašinos ir įrengimai", "Mašinos ir įrengimai"),
                            ("įrenginiai", "Įrenginiai"),
                            ("inventorius", "Inventorius"),
                            ("kitas materialusis turtas", "Kitas materialusis turtas"),
                            (
                                "kitas nematerialusis turtas",
                                "Kitas nematerialusis turtas",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "useful_life_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "asset_account",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "accumulated_depreciation_account",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "depreciation_expense_account",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_asset_groups",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Juodraštis"),
                            ("active", "Eksploatuojamas"),
                            ("sold", "Parduotas"),
                            ("written_off", "Nurašytas"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("operation_start_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "useful_life_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_assets",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="docscanner_app.purchase",
                    ),
                ),
                (
                    "purchase_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="docscanner_app.purchaseline",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="docscanner_app.fixedassetgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FixedAssetOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("acquisition", "Įsigijimas"),
                            ("depreciation", "Nusidėvėjimas"),
                            ("improvement", "Pagerinimas"),
                            ("impairment", "Vertės sumažėjimas"),
                            ("revaluation", "Perkainojimas"),
                            ("sale", "Pardavimas"),
                            ("write_off", "Nurašymas"),
                            ("adjustment", "Koregavimas"),
                        ],
                        max_length=32,
                    ),
                ),
                ("operation_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "book",
                    models.CharField(
                        choices=[("accounting", "Buhalterinis"), ("tax", "Mokestinis")],
                        default="accounting",
                        max_length=16,
                    ),
                ),
                ("period", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="docscanner_app.fixedasset",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_asset_operations",
                        to="docscanner_app.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["operation_date", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="fixedassetgroup",
            constraint=models.UniqueConstraint(
                fields=("company_profile", "category"),
                name="unique_fixed_asset_group_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("inventory_number", ""), _negated=True),
                fields=("company_profile", "inventory_number"),
                name="unique_fixed_asset_inventory_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purchase_line__isnull", True),
                    ("purchase__isnull", False),
                    _connector="OR",
                ),
                name="fixed_asset_line_requires_purchase",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedassetoperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operation_type", "depreciation")),
                fields=("asset", "book", "period"),
                name="unique_fixed_asset_depreciation_period",
            ),
        ),
    ]
