# Generated by Django 5.1.3 on 2026-09-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0176_alter_journalentry_source_type_fixedassetgroup_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="disposal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedassetoperation",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
