# Generated by Django 5.1.3 on 2026-09-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0177_fixedasset_disposal_date_fixedassetoperation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="sale_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sold_fixed_assets",
                to="docscanner_app.invoice",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="sale_invoice_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sold_fixed_assets",
                to="docscanner_app.invoicelineitem",
            ),
        ),
    ]
