# Generated by Django 5.1.3 on 2026-09-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0178_fixedasset_sale_invoice_fixedasset_sale_invoice_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedassetoperation",
            name="extra_months",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fixedassetoperation",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_asset_improvements",
                to="docscanner_app.purchase",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetoperation",
            name="purchase_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_asset_improvements",
                to="docscanner_app.purchaseline",
            ),
        ),
    ]
