# Generated by Django 5.1.3 on 2026-09-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0179_fixedassetoperation_extra_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="fixed_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Jei eilutėje parduodamas ilgalaikis turtas",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_lines",
                to="docscanner_app.fixedasset",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalanceline",
            name="section",
            field=models.CharField(
                choices=[
                    ("balance", "Balansas"),
                    ("bank", "Banko sąskaitos"),
                    ("buyer", "Pirkėjų skolos"),
                    ("supplier", "Tiekėjų skolos"),
                    ("fixed_asset", "Ilgalaikis turtas"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancesection",
            name="section",
            field=models.CharField(
                choices=[
                    ("balance", "Balansas"),
                    ("bank", "Banko sąskaitos"),
                    ("buyer", "Pirkėjų skolos"),
                    ("supplier", "Tiekėjų skolos"),
                    ("fixed_asset", "Ilgalaikis turtas"),
                ],
                max_length=20,
            ),
        ),
    ]
