# Generated by Django 5.1.3 on 2026-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0180_invoicelineitem_fixed_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VatCheckCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("vat_number", models.CharField(max_length=32)),
                ("valid", models.BooleanField()),
                ("name", models.CharField(blank=True, default="", max_length=500)),
                ("address", models.TextField(blank=True, default="")),
                ("checked_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "vat_number"),
                        name="uniq_vat_check_cache",
                    )
                ],
            },
        ),
    ]
