# Generated by Django 5.1.3 on 2026-09-25 07:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0181_vatcheckcache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Pirkimas"),
                    ("sale", "Pardavimas"),
                    ("bank", "Bankas"),
                    ("manual", "Rankinis"),
                    ("opening", "Pradiniai likučiai"),
                    ("fixed_asset", "Ilgalaikis turtas"),
                    ("payroll", "Darbo užmokestis"),
                ],
                max_length=12,
                verbose_name="Šaltinio tipas",
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=68)),
                ("last_name", models.CharField(max_length=68)),
                (
                    "personal_code",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("is_foreigner", models.BooleanField(default=False)),
                (
                    "foreign_code",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                ("sd_series", models.CharField(blank=True, default="", max_length=2)),
                ("sd_number", models.CharField(blank=True, default="", max_length=7)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("iban", models.CharField(blank=True, default="", max_length=34)),
                (
                    "npd_mode",
                    models.CharField(
                        choices=[
                            ("standard", "Taikyti (formulė)"),
                            ("none", "Netaikyti"),
                            ("d30_55", "30-55 % dalyvumo lygis"),
                            ("d0_25", "0-25 % dalyvumo lygis"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("npd_request_date", models.DateField(blank=True, null=True)),
                ("progressive_gpm_request", models.BooleanField(default=False)),
                ("pension_accumulation", models.BooleanField(default=False)),
                (
                    "grindys_exempt_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("other_employer", "Dirba pas kitą darbdavį"),
                            ("pension", "Gauna senatvės / netekto darbingumo pensiją"),
                            ("under_24", "Jaunesnis nei 24 m."),
                            ("participation", "0-55 % dalyvumo lygis"),
                            (
                                "childcare",
                                "Gauna motinystės / tėvystės / vaiko priežiūros išmoką",
                            ),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "onboarding_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Dirba"), ("dismissed", "Atleistas")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=68)),
                ("birth_date", models.DateField()),
                (
                    "personal_code",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                ("has_disability", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="docscanner_app.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["birth_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeYearTotals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "vsd_base",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "gpm_taxable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("limits_used", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_totals",
                        to="docscanner_app.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, default="", max_length=50)),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "sodra_contract_type",
                    models.CharField(
                        choices=[
                            ("01", "Neterminuota"),
                            ("02", "Terminuota"),
                            ("03", "Laikinojo darbo"),
                            ("04", "Pameistrystės"),
                            ("05", "Projektinio darbo"),
                            ("06", "Darbo vietos dalijimosi"),
                            ("07", "Darbo keliems darbdaviams"),
                            ("08", "Sezoninio darbo"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "sodra_contract_subtype",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("probation_months", models.PositiveSmallIntegerField(default=0)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_basis", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Juodraštis"),
                            ("active", "Galioja"),
                            ("terminated", "Nutraukta"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="docscanner_app.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PayCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("earning", "Priskaitymas"),
                            ("compensation", "Kompensacija / pašalpa"),
                            ("in_kind", "Pajamos natūra"),
                            ("deduction", "Išskaita"),
                            ("employer", "Darbdavio įmoka"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calc_method",
                    models.CharField(
                        choices=[
                            ("fixed", "Fiksuota suma"),
                            ("hourly", "Valandinis"),
                            ("multiplier", "Koeficientas"),
                            ("vdu_pct", "% nuo VDU"),
                            ("percent", "Procentas"),
                            ("manual", "Rankinis"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "vdu_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "gpm_mode",
                    models.CharField(
                        choices=[
                            ("standard", "20 / 25 / 32 %"),
                            ("sick_15", "15 % (ligos išmoka)"),
                            ("exempt", "Neapmokestinama"),
                            ("limit", "Neapmokestinama iki metinio limito"),
                            ("dpn_rule", "Dienpinigių taisyklė"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "vmi_income_code",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("in_monthly_npd_base", models.BooleanField(default=True)),
                (
                    "sodra_mode",
                    models.CharField(
                        choices=[
                            ("yes", "Taip"),
                            ("no", "Ne"),
                            ("limit", "Iki metinio limito - ne"),
                            ("aid_5mma", "Iki 5 MMA - ne"),
                        ],
                        default="yes",
                        max_length=20,
                    ),
                ),
                (
                    "vdu_treatment",
                    models.CharField(
                        choices=[
                            ("regular", "Įtraukiama"),
                            ("quarterly_bonus", "Ketvirtinė premija"),
                            ("annual_bonus", "Metinė premija"),
                            ("excluded", "Neįtraukiama"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "annual_limit_key",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("declared_gpm313", models.BooleanField(default=True)),
                (
                    "debit_account",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "credit_account",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = sisteminis kodas",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_codes",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="AbsenceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Kasmetinės atostogos"),
                            ("sick", "Liga"),
                            ("parent_day", "Mamadienis / tėvadienis"),
                            ("unpaid", "Nemokamos atostogos"),
                            ("truancy", "Pravaikšta"),
                            ("downtime", "Prastova"),
                            ("study", "Mokymosi atostogos"),
                            ("donor", "Donorystė"),
                            ("civic", "Valstybinės pareigos"),
                            ("standby", "Pasyvus budėjimas"),
                            ("paternity", "Tėvystės atostogos"),
                            ("childcare", "Vaiko priežiūros atostogos"),
                            ("maternity", "Nėštumo ir gimdymo atostogos"),
                            ("suspension", "Nušalinimas"),
                            ("business_trip", "Komandiruotė"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "work_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Rankinis"),
                            ("request", "Prašymas"),
                            ("sodra_xml", "Sodros XML"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Pateiktas"),
                            ("approved", "Patvirtintas"),
                            ("cancelled", "Atšauktas"),
                        ],
                        default="approved",
                        max_length=12,
                    ),
                ),
                (
                    "sick_leave_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("employer_pays_first_days", models.BooleanField(default=True)),
                (
                    "sodra_reason_code",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continuations",
                        to="docscanner_app.absenceevent",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.employeechild",
                    ),
                ),
                (
                    "pay_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.paycode",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=40)),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_preliminary", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key", "valid_from"],
                "unique_together": {("key", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("regular", "Mėnesio DU"),
                            ("advance", "Avansas"),
                            ("final_settlement", "Galutinis atsiskaitymas"),
                            ("correction", "Korekcija"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Juodraštis"),
                            ("checked", "Patikrinta"),
                            ("approved", "Patvirtinta"),
                            ("paid", "Išmokėta"),
                            ("closed", "Uždaryta"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_runs",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_runs",
                        to="docscanner_app.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("accrual_month", models.DateField()),
                ("sodra_month", models.DateField(blank=True, null=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.employmentcontract",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_lines",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.absenceevent",
                    ),
                ),
                (
                    "pay_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docscanner_app.paycode",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="docscanner_app.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "pay_code__sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PayrollEmployeeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "sodra_base",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "npd_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "npd_sick_part",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "gpm",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "gpm15",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "vsd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "psd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "kaupimas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "employer_vsd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "gar",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "ilg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "grindys_vsd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "grindys_psd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "in_kind",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "payable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "daily_vdu",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "sam_tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "sam_payment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("calc_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_results",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="docscanner_app.payrollrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sodra_insurer_code",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                (
                    "na_group",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                        ],
                        default="I",
                        max_length=3,
                    ),
                ),
                (
                    "na_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.14"), max_digits=5
                    ),
                ),
                ("pays_gar_ilg", models.BooleanField(default=True)),
                (
                    "sick_pay_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("62.06"), max_digits=5
                    ),
                ),
                ("advance_enabled", models.BooleanField(default=False)),
                ("advance_day", models.PositiveSmallIntegerField(default=20)),
                ("salary_day", models.PositiveSmallIntegerField(default=10)),
                (
                    "default_expense_account",
                    models.CharField(default="6304", max_length=10),
                ),
                ("collective_agreement", models.BooleanField(default=False)),
                (
                    "edas_username",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "edas_password",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "manager_name",
                    models.CharField(blank=True, default="", max_length=68),
                ),
                (
                    "preparator_details",
                    models.CharField(blank=True, default="", max_length=68),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_settings",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("lpk_code", models.CharField(blank=True, default="", max_length=6)),
                (
                    "expense_account",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Juodraštis"),
                            ("approved", "Patvirtintas"),
                            ("locked", "Užrakintas"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("code", models.CharField(max_length=5)),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "hour_type",
                    models.CharField(
                        choices=[
                            ("normal", "Įprastos"),
                            ("night", "Naktis"),
                            ("overtime", "Viršvalandžiai"),
                            ("rest_day", "Poilsio diena"),
                            ("holiday", "Švenčių diena"),
                            ("ot_night", "Viršvalandžiai naktį"),
                            ("ot_rest", "Viršvalandžiai poilsio dieną"),
                            ("ot_holiday", "Viršvalandžiai švenčių dieną"),
                        ],
                        default="normal",
                        max_length=12,
                    ),
                ),
                ("is_manual", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.absenceevent",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="docscanner_app.timesheetmonth",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "date"],
            },
        ),
        migrations.CreateModel(
            name="VacationAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("days", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_adjustments",
                        to="docscanner_app.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mon",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                (
                    "tue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                (
                    "wed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                (
                    "thu",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                (
                    "fri",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                (
                    "sat",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=4
                    ),
                ),
                (
                    "sun",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=4
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                (
                    "pay_form",
                    models.CharField(
                        choices=[
                            ("monthly", "Mėnesinė alga"),
                            ("hourly", "Valandinis"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "workload",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=4
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="docscanner_app.employmentcontract",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.position",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.workschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["valid_from"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "status"], name="docscanner__company_c73a20_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeyeartotals",
            unique_together={("employee", "year")},
        ),
        migrations.AddConstraint(
            model_name="paycode",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="uniq_paycode_company_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="paycode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", True)),
                fields=("code",),
                name="uniq_paycode_system_code",
            ),
        ),
        migrations.AddIndex(
            model_name="absenceevent",
            index=models.Index(
                fields=["employee", "start_date", "end_date"],
                name="docscanner__employe_1ffad6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["company", "year", "month"],
                name="docscanner__company_068d48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                fields=["run", "employee"], name="docscanner__run_id_ac41e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollemployeeresult",
            unique_together={("run", "employee")},
        ),
        migrations.AlterUniqueTogether(
            name="timesheetmonth",
            unique_together={("company", "year", "month")},
        ),
        migrations.AddIndex(
            model_name="timesheetentry",
            index=models.Index(
                fields=["timesheet", "employee"], name="docscanner__timeshe_d4e3e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractterms",
            unique_together={("contract", "valid_from")},
        ),
    ]
