# Generated by Django 5.1.3 on 2026-09-26 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0182_alter_journalentry_source_type_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Vyras"), ("F", "Moteris")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="employmentcontract",
            name="annual_leave_days",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="employmentcontract",
            name="work_time_mode",
            field=models.CharField(default="01", max_length=2),
        ),
        migrations.AddField(
            model_name="paycode",
            name="sdup_extra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paycode",
            name="sdup_hours",
            field=models.CharField(default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="paycode",
            name="sdup_total",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="sodra_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="PositionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9.-]+$",
                                "Tik lotyniškos raidės, skaičiai, taškas ir brūkšnys",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("skills", models.PositiveSmallIntegerField(default=3)),
                ("qualification", models.PositiveSmallIntegerField(default=3)),
                ("effort", models.PositiveSmallIntegerField(default=3)),
                ("responsibility", models.PositiveSmallIntegerField(default=3)),
                ("conditions", models.PositiveSmallIntegerField(default=3)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_groups",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.AddField(
            model_name="position",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="docscanner_app.positiongroup",
            ),
        ),
        migrations.CreateModel(
            name="DasDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("approved_date", models.DateField()),
                (
                    "manager_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("html", models.TextField()),
                ("groups_snapshot", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="das_documents",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("company", "version")},
            },
        ),
    ]
