# Generated by Django 5.1.3 on 2026-09-27 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0183_employee_gender_employmentcontract_annual_leave_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractterms",
            name="full_time_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("40"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("complete", "Užpildyta"),
                    ("awaiting_employee", "Laukiama darbuotojo duomenų"),
                ],
                default="complete",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="has_disability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="single_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employmentcontract",
            name="extended_leave_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employmentcontract",
            name="extra_leave_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employmentcontract",
            name="seniority_since",
            field=models.DateField(blank=True, null=True),
        ),
    ]
