# Generated by Django 5.1.3 on 2026-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0184_contractterms_full_time_hours_employee_data_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dasdocument",
            name="extra_terms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employmentcontract",
            name="extra_terms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="contract_city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="manager_position",
            field=models.CharField(blank=True, default="direktorius", max_length=100),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="representation_basis",
            field=models.CharField(
                blank=True, default="įmonės įstatai", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="workplace_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
