# Generated by Django 5.1.3 on 2026-09-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0185_dasdocument_extra_terms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "Darbo sutartis"),
                            ("amendment", "Susitarimas dėl sutarties pakeitimo"),
                            ("order", "Įsakymas"),
                            ("request", "Prašymas"),
                            ("other", "Kita"),
                        ],
                        default="contract",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("number", models.CharField(blank=True, default="", max_length=50)),
                ("html", models.TextField(blank=True, default="")),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="payroll/documents/%Y/%m/"
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sign_method",
                    models.CharField(
                        choices=[
                            ("paper", "Pasirašyta popieriuje"),
                            ("electronic", "Elektroniniu parašu"),
                            ("external", "Pasirašyta ne DokSkenas"),
                        ],
                        default="paper",
                        max_length=12,
                    ),
                ),
                ("employee_signed", models.BooleanField(default=False)),
                ("employer_signed", models.BooleanField(default=False)),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="docscanner_app.employmentcontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="docscanner_app.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
