# Generated by Django 5.1.3 on 2026-09-29 06:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0187_employeeaccount_employee_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Kasmetinės atostogos"),
                            ("parent_day", "Mamadienis / tėvadienis"),
                            ("unpaid", "Nemokamos atostogos"),
                            (
                                "dismissal",
                                "Darbo sutarties nutraukimas darbuotojo iniciatyva",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "work_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Laukia"),
                            ("approved", "Patvirtinta"),
                            ("rejected", "Atmesta"),
                            ("cancelled", "Atšaukta"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("html", models.TextField(blank=True, default="")),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "submitted_user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "absence_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="docscanner_app.absenceevent",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="docscanner_app.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="docscanner__employe_26cb27_idx",
                    )
                ],
            },
        ),
    ]
