# Generated by Django 5.1.3 on 2026-09-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0188_employeerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("SAM", "SAM"),
                            ("GPM313", "GPM313"),
                            ("1-SD", "1-SD"),
                            ("2-SD", "2-SD"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("content", models.TextField(blank=True, default="")),
                ("errors", models.JSONField(blank=True, default=list)),
                ("manual_values", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Paruošta"),
                            ("error", "Yra klaidų"),
                            ("submitted", "Pateikta"),
                            ("accepted", "Priimta"),
                            ("rejected", "Atmesta"),
                        ],
                        default="ready",
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_declarations",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="docscanner_app.employmentcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "form"],
                "indexes": [
                    models.Index(
                        fields=["company", "form", "year", "month"],
                        name="docscanner__company_b71d3c_idx",
                    )
                ],
            },
        ),
    ]
