# Generated by Django 5.1.3 on 2026-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0189_payrolldeclaration"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sodra_kodas",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
