# Generated by Django 5.1.3 on 2026-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0190_company_sodra_kodas"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("last_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_changed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
