# Generated by Django 5.1.3 on 2026-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0191_syncstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrolldeclaration",
            name="external_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrolldeclaration",
            name="external_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="payrolldeclaration",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="vmi_ws_password",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="vmi_ws_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
