# Generated by Django 5.1.3 on 2026-10-02 08:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0192_payrolldeclaration_external_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="advance_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pay_once_a_month",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_lines",
                to="docscanner_app.employee",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="advance_percent",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="payout_account",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("document", "Dokumentas"),
                    ("advance", "Avansas"),
                    ("writeoff", "Nurašymas"),
                    ("payroll", "Darbo užmokestis"),
                ],
                default="document",
                max_length=12,
                verbose_name="Tipas",
            ),
        ),
        migrations.CreateModel(
            name="PayrollPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("employee", "Atlyginimas"),
                            ("advance", "Avansas"),
                            ("gpm", "GPM (VMI)"),
                            ("sodra", "Sodra"),
                            ("deduction", "Išskaita"),
                        ],
                        max_length=12,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "recipient_iban",
                    models.CharField(blank=True, default="", max_length=34),
                ),
                (
                    "recipient_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "imokos_kodas",
                    models.CharField(blank=True, default="", max_length=6),
                ),
                ("purpose", models.CharField(blank=True, default="", max_length=140)),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=35
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Laukia"),
                            ("sent", "Išsiųsta į banką"),
                            ("partial", "Dalinai sumokėta"),
                            ("paid", "Sumokėta"),
                            ("cancelled", "Atšaukta"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payments",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payments",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="docscanner_app.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "kind", "id"],
            },
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payroll_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="docscanner_app.payrollpayment",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["company", "year", "month"],
                name="docscanner__company_9c6263_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["company", "status"], name="docscanner__company_3153c1_idx"
            ),
        ),
    ]
