# Generated by Django 5.1.3 on 2026-10-02 14:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0193_employee_advance_amount_employee_pay_once_a_month_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollpayment",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PayrollPaymentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg_id", models.CharField(max_length=35, unique=True)),
                ("debtor_iban", models.CharField(max_length=34)),
                (
                    "debtor_account",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("execution_date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("xml", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payment_batches",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="docscanner_app.payrollpaymentbatch",
            ),
        ),
    ]
