# Generated by Django 5.1.3 on 2026-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0194_payrollpayment_sent_at_payrollpaymentbatch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="El. paštas (jonas@gmail.com) arba visas domenas (@domenas.lt). Normalizuojama automatiškai.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Užblokuotas el. paštas",
                "verbose_name_plural": "Užblokuoti el. paštai",
            },
        ),
    ]
