# Generated by Django 5.1.3 on 2026-10-04 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0195_blockedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractterms",
            name="work_regime",
            field=models.CharField(
                choices=[
                    ("standard", "Standartinė"),
                    ("summed", "Suminė darbo laiko apskaita"),
                ],
                default="standard",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="roster_publish_days",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="summed_period_anchor",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="summed_period_months",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="EmployeeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("color", models.CharField(blank=True, default="", max_length=9)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_tags",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="docscanner_app.employeetag"
            ),
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Juodraštis"), ("published", "Paskelbtas")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="docscanner_app.companyprofile",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("target", models.JSONField(blank=True, default=dict)),
                ("target2", models.JSONField(blank=True, default=dict)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("hard", models.BooleanField(default=True)),
                ("weight", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=4)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                ("color", models.CharField(blank=True, default="", max_length=9)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_types",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="RosterAck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_acks",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acks",
                        to="docscanner_app.roster",
                    ),
                ),
            ],
            options={
                "unique_together": {("roster", "employee", "version")},
            },
        ),
        migrations.CreateModel(
            name="ShiftPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("avoid", "Nenori dirbti"),
                            ("want", "Nori dirbti"),
                            ("day_off", "Prašo laisvos dienos"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(default="savitarna", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_preferences",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docscanner_app.shifttype",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="docscanner__employe_c97b8a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RosterShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                ("locked", models.BooleanField(default=False)),
                ("source", models.CharField(default="manual", max_length=10)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_shifts",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="docscanner_app.roster",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="docscanner_app.shifttype",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="docscanner__employe_b8545a_idx",
                    )
                ],
            },
        ),
    ]
