# Generated by Django 5.1.3 on 2026-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0196_contractterms_work_regime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="summed_overtime_to_vacation",
            field=models.BooleanField(default=False),
        ),
    ]
