# Generated by Django 5.1.3 on 2026-10-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0197_employee_summed_overtime_to_vacation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RosterWeekTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("items", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_week_templates",
                        to="docscanner_app.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RosterSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("min_staff", models.PositiveSmallIntegerField(default=1)),
                ("max_staff", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="docscanner_app.roster",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docscanner_app.shifttype",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "shift_type__start_time"],
                "unique_together": {("roster", "date", "shift_type")},
            },
        ),
    ]
