# Generated by Django 5.1.3 on 2026-10-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0198_rosterweektemplate_rosterslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="pending_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="roster",
            name="published_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="roster",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Juodraštis"),
                    ("published", "Paskelbtas"),
                    ("editing", "Keičiamas"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RosterChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("old", models.JSONField(blank=True, null=True)),
                ("new", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("late", models.BooleanField(default=False)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_changes",
                        to="docscanner_app.employee",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="docscanner_app.roster",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "employee_id", "date"],
            },
        ),
    ]
