# Generated by Django 5.1.3 on 2026-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "docscanner_app",
            "0199_roster_pending_reason_roster_published_snapshot_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerequest",
            name="answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="employeerequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("vacation", "Kasmetinės atostogos"),
                    ("parent_day", "Mamadienis / tėvadienis"),
                    ("unpaid", "Nemokamos atostogos"),
                    ("dismissal", "Darbo sutarties nutraukimas darbuotojo iniciatyva"),
                    ("pay_info", "Informacija apie darbo užmokestį"),
                ],
                max_length=20,
            ),
        ),
    ]
