# Generated by Django 5.1.3 on 2026-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docscanner_app", "0200_employeerequest_answer_alter_employeerequest_kind"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "regular")),
                fields=("company", "year", "month", "kind"),
                name="uniq_payroll_regular_run",
            ),
        ),
    ]
